import { SeedProduct } from './data';

export const PRODUCTS_PART_2: SeedProduct[] = [
  // 37-50: KITCHEN APPLIANCES
  {
    name: "Nasgas Kitchen Hood KHD-275",
    slug: "nasgas-kitchen-hood-khd-275",
    brand: "Nasgas",
    category: "Kitchen Appliances",
    subcategory: "Kitchen Hoods",
    sku: "HC-KIT-001",
    description: "Nasgas KHD-275 premium designer kitchen hood features curved tempered glass, 1000m3/hr high-suction copper motor, touch controls with gesture sensing, and baffle filters.",
    shortDescription: "Curved tempered glass kitchen hood with motion hand-wave gesture control and high suction copper motor.",
    price: 36000,
    oldPrice: 40000,
    discountPercentage: 10,
    stock: 12,
    stockStatus: "in_stock",
    images: [
      "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?auto=format&fit=crop&w=800&q=80"
    ],
    thumbnail: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80",
    specifications: { "Suction Power": "1000 m3/hr", "Motor": "100% Pure Copper Heavy Motor", "Controls": "Touch + Hand Gesture Sensor", "Filters": "Stainless Steel Baffle Filter" },
    features: ["Hand Wave Gesture Control", "Auto Clean Heat Wash Technology", "Bright Energy Saving LED Spots"],
    warranty: "1 Year Official Nasgas Warranty",
    tags: ["Nasgas", "Kitchen Hood", "KHD-275", "Gesture Control"],
    isFeatured: true,
    isDeal: true,
    isNew: false,
    rating: 4.8,
    reviewCount: 21,
    weight: "14 kg",
    dimensions: "900 x 500 x 530 mm",
    color: "Black Glass & Stainless Steel",
    capacity: "90 cm Hood",
    model: "KHD-275",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Nasgas Kitchen Hood KHD-265",
    slug: "nasgas-kitchen-hood-khd-265",
    brand: "Nasgas",
    category: "Kitchen Appliances",
    subcategory: "Kitchen Hoods",
    sku: "HC-KIT-002",
    description: "Nasgas KHD-265 slim profile hood with stainless steel finish, push-button controls, twin LED lights, and washable aluminum grease filters.",
    shortDescription: "Slim stainless steel hood with dual blower extraction and bright illumination.",
    price: 31000,
    oldPrice: 35000,
    discountPercentage: 11,
    stock: 15,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80",
    specifications: { "Suction Power": "850 m3/hr", "Body": "Brushed Stainless Steel", "Noise Level": "Under 56 dB" },
    features: ["Dual High Speed Blower", "Dishwasher Safe Aluminum Filters", "Compact Under-Cabinet Mount"],
    warranty: "1 Year Official Warranty",
    tags: ["Nasgas", "Kitchen Hood", "Slim Hood"],
    isFeatured: false,
    isDeal: false,
    isNew: false,
    rating: 4.6,
    reviewCount: 14,
    weight: "12 kg",
    dimensions: "900 x 480 x 480 mm",
    color: "Stainless Steel",
    capacity: "90 cm",
    model: "KHD-265",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Nasgas Cooking Range SG-324 5-Burner",
    slug: "nasgas-cooking-range-sg-324-5-burner",
    brand: "Nasgas",
    category: "Kitchen Appliances",
    subcategory: "Cooking Ranges",
    sku: "HC-KIT-003",
    description: "Nasgas SG-324 heavy-gauge 5-burner cooking range with double glass door, rotisserie turnspit grill, high-flame brass burners, and magnetic safety valve.",
    shortDescription: "Heavy-gauge 5-burner luxury cooking range with motorized rotisserie oven and top glass lid.",
    price: 68000,
    oldPrice: 75000,
    discountPercentage: 9,
    stock: 8,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80",
    specifications: { "Burners": "5 Heavy Brass Burners", "Oven Capacity": "Large 90L Capacity", "Grill": "Motorized Rotisserie Turnspit", "Ignition": "Automatic Piezo Electric" },
    features: ["Double Insulated Oven Chamber", "Cast Iron Heavy Pan Supports", "Interior Oven Lamp & Timer"],
    warranty: "1 Year Official Nasgas Warranty",
    tags: ["Nasgas", "Cooking Range", "5 Burner", "SG-324"],
    isFeatured: true,
    isDeal: true,
    isNew: false,
    rating: 4.9,
    reviewCount: 18,
    weight: "58 kg",
    dimensions: "900 x 600 x 850 mm",
    color: "Silver & Black Glass",
    capacity: "5 Burners + 90L Oven",
    model: "SG-324",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Nasgas Hob DG-GN2 3-Burner Glass Hob",
    slug: "nasgas-hob-dg-gn2-3-burner-glass-hob",
    brand: "Nasgas",
    category: "Kitchen Appliances",
    subcategory: "Built-in Hobs",
    sku: "HC-KIT-004",
    description: "Nasgas DG-GN2 built-in 3-burner gas hob with 8mm thick toughened black safety glass, European brass burners, and battery pulse auto-ignition.",
    shortDescription: "8mm toughened safety glass built-in hob with battery auto-ignition and heavy cast iron trivets.",
    price: 29000,
    oldPrice: 33000,
    discountPercentage: 12,
    stock: 16,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80",
    specifications: { "Burners": "3 Brass Burners (1 Wok + 2 Medium)", "Glass": "8mm Thermal Shock Resistant", "Ignition": "Battery Pulse Ignition" },
    features: ["High Heat Output Triple Ring Wok Burner", "Heavy Duty Non-Slip Cast Iron Pan Stands", "Easy Wipe Stain-Resistant Glass"],
    warranty: "1 Year Official Warranty",
    tags: ["Nasgas", "Built-in Hob", "3 Burner", "Glass Hob"],
    isFeatured: false,
    isDeal: true,
    isNew: true,
    rating: 4.8,
    reviewCount: 19,
    weight: "11 kg",
    dimensions: "780 x 450 x 85 mm",
    color: "Tempered Black Glass",
    capacity: "3 Burners",
    model: "DG-GN2",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Midas Italy Infrax-3 Hot Plate MI-101",
    slug: "midas-italy-infrax-3-hot-plate-mi-101",
    brand: "Midas",
    category: "Kitchen Appliances",
    subcategory: "Hot Plates",
    sku: "HC-KIT-005",
    description: "Midas Italy Infrax-3 MI-101 infrared ceramic hot plate works with all cookware types (clay, steel, aluminum, glass) with variable touch temperature adjustment.",
    shortDescription: "Versatile infrared cooker suitable for any flat cookware with instant high-efficiency ceramic heat.",
    price: 13500,
    oldPrice: 15500,
    discountPercentage: 13,
    stock: 22,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80",
    specifications: { "Power": "2200W", "Heating Tech": "Infrared Ceramic Coil", "Cookware": "Works with ALL pots and pans" },
    features: ["Compatible with All Cookware Materials", "Digital LED Display & Touch Slider", "Overheat & Voltage Protection"],
    warranty: "1 Year Brand Warranty",
    tags: ["Midas", "Hot Plate", "Infrared", "Cooker"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.7,
    reviewCount: 25,
    weight: "2.8 kg",
    dimensions: "360 x 280 x 65 mm",
    color: "Crystal Black & Bronze",
    capacity: "2200W",
    model: "MI-101",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "RAF 3500W Infrared Cooker R-8019",
    slug: "raf-3500w-infrared-cooker-r-8019",
    brand: "RAF",
    category: "Kitchen Appliances",
    subcategory: "Hot Plates",
    sku: "HC-KIT-006",
    description: "RAF R-8019 3500W ultra-high power infrared cooker features German technology microcrystalline plate, fast water boiling in 2 minutes, and child safety lock.",
    shortDescription: "Ultra-fast 3500W commercial power electric infrared cooker with timer and touch control.",
    price: 16500,
    oldPrice: 19000,
    discountPercentage: 13,
    stock: 18,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80",
    specifications: { "Wattage": "3500W High Output", "Plate": "A-Grade Microcrystalline Glass", "Timer": "Up to 180 Minutes" },
    features: ["Rapid High-Temperature Cooking", "Multi-Stage Firepower Selection", "No Radiation Clean Heat"],
    warranty: "1 Year Replacement Warranty",
    tags: ["RAF", "3500W", "Infrared Cooker"],
    isFeatured: false,
    isDeal: false,
    isNew: true,
    rating: 4.8,
    reviewCount: 17,
    weight: "3.2 kg",
    dimensions: "380 x 300 x 70 mm",
    color: "Gold & Black",
    capacity: "3500W",
    model: "R-8019",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Haier HMW-20MHES Microwave Oven 20L",
    slug: "haier-hmw-20mhes-microwave-oven-20l",
    brand: "Haier",
    category: "Microwaves",
    subcategory: "Solo Microwave",
    sku: "HC-KIT-007",
    description: "Haier HMW-20MHES 20-liter solo microwave oven with mechanical rotary knobs, 5 power cooking levels, express defrost, and easy-clean cavity.",
    shortDescription: "Durable 20L mechanical knob microwave oven for quick daily heating and defrosting.",
    price: 24000,
    oldPrice: 27000,
    discountPercentage: 11,
    stock: 20,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "20 Liters", "Power": "700W Microwave", "Control": "Dual Mechanical Rotary Dials" },
    features: ["5 Power Level Settings", "Speed Defrost by Weight", "Turntable Glass Tray"],
    warranty: "1 Year Official Haier Warranty",
    tags: ["Haier", "Microwave", "20L", "Solo"],
    isFeatured: true,
    isDeal: true,
    isNew: false,
    rating: 4.7,
    reviewCount: 32,
    weight: "10.5 kg",
    dimensions: "440 x 330 x 258 mm",
    color: "Silver",
    capacity: "20 Liters",
    model: "HMW-20MHES",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Haier Air Fryer 5L HAF50DB",
    slug: "haier-air-fryer-5l-haf50db",
    brand: "Haier",
    category: "Kitchen Appliances",
    subcategory: "Air Fryers",
    sku: "HC-KIT-008",
    description: "Haier HAF50DB 5-liter digital air fryer with 360-degree rapid air heat circulation, 8 preset cooking menus, viewing window, and non-stick basket.",
    shortDescription: "5-liter digital air fryer with transparent visual window and 85% oil reduction.",
    price: 26000,
    oldPrice: 29500,
    discountPercentage: 12,
    stock: 15,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "5.0 Liters", "Power": "1500W", "Display": "Digital Touch Screen" },
    features: ["Visual Clear-View Window", "360° Cyclone Air Heating", "Dishwasher Safe Non-Stick Coating"],
    warranty: "1 Year Official Warranty",
    tags: ["Haier", "Air Fryer", "5L", "Digital"],
    isFeatured: true,
    isDeal: false,
    isNew: true,
    rating: 4.9,
    reviewCount: 27,
    weight: "4.8 kg",
    dimensions: "320 x 270 x 300 mm",
    color: "Glossy Black & Gold",
    capacity: "5 Liters",
    model: "HAF50DB",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Canon Built-in Hob 3-Burner Flame Failure",
    slug: "canon-built-in-hob-3-burner-flame-failure",
    brand: "Canon",
    category: "Kitchen Appliances",
    subcategory: "Built-in Hobs",
    sku: "HC-KIT-009",
    description: "Canon 3-burner tempered glass hob featuring Italian thermocouple flame failure device that automatically cuts off gas supply if flame blows out.",
    shortDescription: "Safety-first tempered glass gas hob with European flame failure safety sensor.",
    price: 33000,
    oldPrice: 37000,
    discountPercentage: 11,
    stock: 11,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80",
    specifications: { "Safety": "Flame Failure Device (FFD) on all burners", "Glass": "8mm Toughened Glass", "Ignition": "Continuous Electronic Ignition" },
    features: ["Gas Leak Protection Flame Failure Sensors", "Ergonomic Front Metal Control Knobs", "Cast Iron Heavy Duty Supports"],
    warranty: "1 Year Official Canon Warranty",
    tags: ["Canon", "Built-in Hob", "Flame Failure", "Safe"],
    isFeatured: false,
    isDeal: false,
    isNew: false,
    rating: 4.8,
    reviewCount: 16,
    weight: "12 kg",
    dimensions: "860 x 500 x 90 mm",
    color: "Black Glass",
    capacity: "3 Burners",
    model: "C-HOB-300",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Nasgas Built-in Oven Gas & Electric BO-501",
    slug: "nasgas-built-in-oven-gas-electric-bo-501",
    brand: "Nasgas",
    category: "Kitchen Appliances",
    subcategory: "Built-in Ovens",
    sku: "HC-KIT-010",
    description: "Nasgas BO-501 built-in kitchen oven with dual gas and electric heating elements, convection fan baking, triple-glazed cool-touch door, and rotisserie.",
    shortDescription: "Dual fuel gas & electric built-in oven with convection fan and triple-glazed door.",
    price: 74000,
    oldPrice: 82000,
    discountPercentage: 10,
    stock: 7,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "65 Liters", "Heating Modes": "Gas Bake + Electric Grill + Convection Fan", "Door": "Triple Layer Glass Cool Touch" },
    features: ["Even Temperature Convection Fan", "Precision Digital Countdown Timer", "Easy Clean Enamel Interior"],
    warranty: "1 Year Official Nasgas Warranty",
    tags: ["Nasgas", "Built-in Oven", "Dual Fuel"],
    isFeatured: true,
    isDeal: false,
    isNew: true,
    rating: 4.9,
    reviewCount: 13,
    weight: "34 kg",
    dimensions: "595 x 595 x 550 mm",
    color: "Stainless Steel & Black Glass",
    capacity: "65 Liters",
    model: "BO-501",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Dawlance Built-in Oven DBO-450 G",
    slug: "dawlance-built-in-oven-dbo-450-g",
    brand: "Dawlance",
    category: "Kitchen Appliances",
    subcategory: "Built-in Ovens",
    sku: "HC-KIT-011",
    description: "Dawlance DBO-450 G premium built-in oven offering uniform convection heating, defrost function, motorized turnspit, and easy sliding shelves.",
    shortDescription: "Premium European styled built-in kitchen oven with multi-function baking programs.",
    price: 79000,
    oldPrice: 88000,
    discountPercentage: 10,
    stock: 6,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "70 Liters", "Oven Functions": "8 Multi-Bake Settings", "Glass Door": "Removable Inner Glass for Cleaning" },
    features: ["Rotisserie Turnspit for Whole Chicken", "Dynamic Cooling Fan System", "Catalytic Self-Clean Wall Liners"],
    warranty: "1 Year Official Warranty",
    tags: ["Dawlance", "Built-in Oven", "Baking"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.8,
    reviewCount: 15,
    weight: "36 kg",
    dimensions: "595 x 595 x 565 mm",
    color: "Black Mirror Glass",
    capacity: "70 Liters",
    model: "DBO-450-G",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Canon Kitchen Hood C-90 Curved Glass",
    slug: "canon-kitchen-hood-c-90-curved-glass",
    brand: "Canon",
    category: "Kitchen Appliances",
    subcategory: "Kitchen Hoods",
    sku: "HC-KIT-012",
    description: "Canon C-90 curved glass chimney kitchen hood with 3-speed copper motor, high airflow suction, and washable oil baffle filters.",
    shortDescription: "Elegant curved glass 90cm kitchen chimney with copper motor and LED illumination.",
    price: 32000,
    oldPrice: 36000,
    discountPercentage: 11,
    stock: 14,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80",
    specifications: { "Suction Rate": "900 m3/hr", "Controls": "3 Speed Push Buttons", "Lighting": "Dual LED Lamps" },
    features: ["High Capacity Pure Copper Motor", "Washable Stainless Steel Filter", "Curved Toughened Glass Canopy"],
    warranty: "1 Year Canon Official Warranty",
    tags: ["Canon", "Kitchen Hood", "Chimney"],
    isFeatured: false,
    isDeal: false,
    isNew: false,
    rating: 4.6,
    reviewCount: 14,
    weight: "13.5 kg",
    dimensions: "900 x 500 x 500 mm",
    color: "Glass & Stainless Steel",
    capacity: "90 cm",
    model: "C-90",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Dawlance Microwave Oven MD-300 Baking Grill 30L",
    slug: "dawlance-microwave-oven-md-300-baking-grill-30l",
    brand: "Dawlance",
    category: "Microwaves",
    subcategory: "Grill Microwave",
    sku: "HC-KIT-013",
    description: "Dawlance MD-300 30-liter convection & grill microwave oven with Pakistani Recipe auto-cook menus (Biryani, Qorma, Tikka), and motorized grill heater.",
    shortDescription: "30L Large Convection Grill microwave with built-in Pakistani recipe cooking presets.",
    price: 37000,
    oldPrice: 42000,
    discountPercentage: 12,
    stock: 13,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "30 Liters", "Heating": "Convection + Grill + Microwave", "Programs": "Pakistani Menu Presets" },
    features: ["Built-in Chef Menu for Pakistani Cuisines", "Rotisserie & Grill Rack Included", "Child Safety Lock System"],
    warranty: "1 Year Official Warranty",
    tags: ["Dawlance", "Microwave", "30L", "Grill"],
    isFeatured: true,
    isDeal: true,
    isNew: false,
    rating: 4.8,
    reviewCount: 22,
    weight: "15.2 kg",
    dimensions: "520 x 410 x 310 mm",
    color: "Mirror Black",
    capacity: "30 Liters",
    model: "MD-300",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "PEL Microwave Oven Classic 23L PMO-23",
    slug: "pel-microwave-oven-classic-23l-pmo-23",
    brand: "PEL",
    category: "Microwaves",
    subcategory: "Solo Microwave",
    sku: "HC-KIT-014",
    description: "PEL PMO-23 23-liter microwave oven with high efficiency magnetron, antibacterial internal enamel, and quick defrost mode.",
    shortDescription: "23-liter everyday microwave with uniform microwave distribution and durable cavity.",
    price: 27000,
    oldPrice: 30000,
    discountPercentage: 10,
    stock: 16,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "23 Liters", "Power": "800W", "Timer": "35 Minute Cooking Timer" },
    features: ["Antibacterial Easy-Wipe Cavity", "Defrost by Weight and Time", "Compact Family Sizing"],
    warranty: "1 Year PEL Warranty",
    tags: ["PEL", "Microwave", "23L"],
    isFeatured: false,
    isDeal: false,
    isNew: false,
    rating: 4.6,
    reviewCount: 15,
    weight: "11.8 kg",
    dimensions: "480 x 360 x 280 mm",
    color: "White & Black",
    capacity: "23 Liters",
    model: "PMO-23",
    installationAvailable: false,
    deliveryAvailable: true
  },

  // 51-58: WASHING MACHINES / DRYERS
  {
    name: "Nasgas NGD-201 Dryer Heavy Duty 10KG",
    slug: "nasgas-ngd-201-dryer-heavy-duty-10kg",
    brand: "Nasgas",
    category: "Washing Machines",
    subcategory: "Spin Dryers",
    sku: "HC-WM-001",
    description: "Nasgas NGD-201 heavy-duty spin dryer with 10KG capacity, high-speed 1400 RPM spin, rust-proof plastic body, and anti-vibration shock balance.",
    shortDescription: "10KG High speed spin dryer extracting up to 95% water in 5 minutes with rust-free body.",
    price: 24000,
    oldPrice: 27000,
    discountPercentage: 11,
    stock: 14,
    stockStatus: "in_stock",
    images: [
      "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80"
    ],
    thumbnail: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "10 KG", "Spin Speed": "1400 RPM", "Body": "Virgin Plastic Rust Proof", "Motor": "Pure Copper Winding" },
    features: ["Quick 5-Minute High Spin Drying", "Shock Balancing Dynamic Suspension", "Rust and Corrosion Proof Cabinet"],
    warranty: "2 Years Motor Warranty, 1 Year Parts",
    tags: ["Nasgas", "Dryer", "10KG", "NGD-201"],
    isFeatured: true,
    isDeal: true,
    isNew: false,
    rating: 4.8,
    reviewCount: 20,
    weight: "16 kg",
    dimensions: "490 x 490 x 870 mm",
    color: "White & Blue",
    capacity: "10 KG",
    model: "NGD-201",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Haier Automatic Washing Machine HWM 90-1789 9KG",
    slug: "haier-automatic-washing-machine-hwm-90-1789-9kg",
    brand: "Haier",
    category: "Washing Machines",
    subcategory: "Fully Automatic",
    sku: "HC-WM-002",
    description: "Haier HWM 90-1789 9KG top-load fully automatic washing machine with Pillow Drum fabric care, Storm Wash dual pulsator, and near-zero water pressure startup.",
    shortDescription: "9KG Top-load fully automatic with Pillow Drum fabric protection and low water pressure support.",
    price: 78000,
    oldPrice: 86000,
    discountPercentage: 9,
    stock: 12,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "9.0 KG", "Type": "Top Load Fully Automatic", "Drum": "Stainless Steel Pillow Drum", "Water Pressure": "Works on 0.001 Mpa Near Zero Pressure" },
    features: ["Near-Zero Water Pressure Startup", "Soft Close Hydraulic Glass Lid", "Dual Magic Lint Filter"],
    warranty: "10 Years Motor Warranty, 1 Year Parts",
    tags: ["Haier", "Automatic", "9KG", "Pillow Drum"],
    isFeatured: true,
    isDeal: true,
    isNew: true,
    rating: 4.9,
    reviewCount: 31,
    weight: "38 kg",
    dimensions: "580 x 590 x 960 mm",
    color: "Titanium Grey",
    capacity: "9 KG",
    model: "HWM-90-1789",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Dawlance Automatic Washing Machine DWT 260 C LVS 10KG",
    slug: "dawlance-automatic-washing-machine-dwt-260-c-lvs-10kg",
    brand: "Dawlance",
    category: "Washing Machines",
    subcategory: "Fully Automatic",
    sku: "HC-WM-003",
    description: "Dawlance DWT 260 C LVS 10KG fully automatic washing machine with Low Voltage Operation down to 150V, Pro Fabric drum, and triple waterfall wash.",
    shortDescription: "10KG LVS Automatic Washing Machine running smoothly even on 150V low voltage.",
    price: 84000,
    oldPrice: 93000,
    discountPercentage: 10,
    stock: 10,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "10 KG", "Voltage": "LVS 150V Operation", "Pulsator": "Extreme Water Fall 3D Flow" },
    features: ["Low Voltage Startup Protection", "Child Safety Lock & Memory Recall", "E-Care Gentle Fabric Washing"],
    warranty: "10 Years Motor Warranty",
    tags: ["Dawlance", "Automatic", "10KG", "LVS"],
    isFeatured: true,
    isDeal: false,
    isNew: false,
    rating: 4.8,
    reviewCount: 24,
    weight: "41 kg",
    dimensions: "600 x 610 x 990 mm",
    color: "Metallic Silver",
    capacity: "10 KG",
    model: "DWT-260-C-LVS",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Super Asia Washing Machine SA-240 Super Twin Tub",
    slug: "super-asia-washing-machine-sa-240-super-twin-tub",
    brand: "Super Asia",
    category: "Washing Machines",
    subcategory: "Twin Tub Semi-Automatic",
    sku: "HC-WM-004",
    description: "Super Asia SA-240 twin tub semi-automatic washing machine featuring shock and rust-proof high grade plastic body, powerful copper motor, and turbo double storm pulsator.",
    shortDescription: "Heavy-duty twin tub washer and spinner with shock-proof body and copper motor.",
    price: 36000,
    oldPrice: 40000,
    discountPercentage: 10,
    stock: 18,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "9 KG Wash + 7 KG Spin", "Body": "High Impact Virgin Plastic", "Motor": "Super Asia Pure Copper Motor" },
    features: ["Double Waterfall Scrubbing Action", "Heavy Duty Lint Trapper", "Low Electricity Consumption"],
    warranty: "2 Years Motor Warranty, 1 Year Parts",
    tags: ["Super Asia", "Twin Tub", "Semi-Automatic"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.7,
    reviewCount: 28,
    weight: "26 kg",
    dimensions: "820 x 480 x 980 mm",
    color: "White & Maroon",
    capacity: "9 KG / 7 KG",
    model: "SA-240",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Samsung Washing Machine WA80T5160 8KG Inverter",
    slug: "samsung-washing-machine-wa80t5160-8kg-inverter",
    brand: "Samsung",
    category: "Washing Machines",
    subcategory: "Fully Automatic",
    sku: "HC-WM-005",
    description: "Samsung WA80T5160 top load automatic washing machine with Digital Inverter Motor, Wobble Technology tangle-free wash, and Magic Dispenser dissolving detergent completely.",
    shortDescription: "Samsung Digital Inverter Top Load with Wobble anti-tangle pulsator and quiet motor.",
    price: 92000,
    oldPrice: 102000,
    discountPercentage: 10,
    stock: 9,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "8.0 KG", "Motor": "Digital Inverter 10 Year Warranty", "Technology": "Wobble Pulsator Care" },
    features: ["Wobble Care Prevents Fabric Tangling", "Magic Filter Traps Fluff & Debris", "Eco Tub Clean Maintenance Alert"],
    warranty: "10 Years Inverter Motor Warranty",
    tags: ["Samsung", "Wobble", "Inverter", "8KG"],
    isFeatured: true,
    isDeal: false,
    isNew: true,
    rating: 4.9,
    reviewCount: 21,
    weight: "37 kg",
    dimensions: "540 x 568 x 988 mm",
    color: "Lavender Gray",
    capacity: "8 KG",
    model: "WA80T5160",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Kenwood Washing Machine KWM-950 Semi-Auto",
    slug: "kenwood-washing-machine-kwm-950-semi-auto",
    brand: "Kenwood",
    category: "Washing Machines",
    subcategory: "Twin Tub Semi-Automatic",
    sku: "HC-WM-006",
    description: "Kenwood KWM-950 twin tub semi-automatic machine with transparent glass cover, high-capacity wash basin, and double motor thermal protection.",
    shortDescription: "High-grade British designed twin tub washer with thermal protector safety.",
    price: 39000,
    oldPrice: 43000,
    discountPercentage: 9,
    stock: 11,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "9.5 KG", "Top Cover": "Tempered Toughened Glass", "Buzzer": "Cycle End Buzzer" },
    features: ["Heavy Duty Spin Extractor", "Thermal Motor Cutoff Overheat Guard", "Spacious Easy Loading Basin"],
    warranty: "2 Years Motor Warranty",
    tags: ["Kenwood", "Twin Tub", "KWM-950"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.7,
    reviewCount: 17,
    weight: "27 kg",
    dimensions: "830 x 490 x 990 mm",
    color: "White & Black Glass",
    capacity: "9.5 KG",
    model: "KWM-950",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "PEL Washing Machine PAWM-1100 Auto 11KG",
    slug: "pel-washing-machine-pawm-1100-auto-11kg",
    brand: "PEL",
    category: "Washing Machines",
    subcategory: "Fully Automatic",
    sku: "HC-WM-007",
    description: "PEL PAWM-1100 11KG jumbo automatic washing machine engineered for large Pakistani duvet covers, blankets, and large laundry loads with Fuzzy Logic auto-balancing.",
    shortDescription: "11KG Jumbo drum automatic washer perfect for bedsheets and blanket washing.",
    price: 86000,
    oldPrice: 95000,
    discountPercentage: 9,
    stock: 8,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "11 KG Jumbo Drum", "Logic": "Fuzzy Logic Smart Sensors", "Drum": "Diamond Honeycomb Drum" },
    features: ["Blanket & Heavy Quilt Program", "Auto Power-Off Standby Zero Power", "High Spin Extraction 800 RPM"],
    warranty: "10 Years Motor Warranty",
    tags: ["PEL", "Automatic", "11KG", "Jumbo"],
    isFeatured: false,
    isDeal: false,
    isNew: true,
    rating: 4.8,
    reviewCount: 15,
    weight: "43 kg",
    dimensions: "620 x 630 x 1010 mm",
    color: "Dark Silver",
    capacity: "11 KG",
    model: "PAWM-1100",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Midea Washing Machine Front Load 8KG Inverter",
    slug: "midea-washing-machine-front-load-8kg-inverter",
    brand: "Midea",
    category: "Washing Machines",
    subcategory: "Front Load Automatic",
    sku: "HC-WM-008",
    description: "Midea 8KG Front Load Washing Machine with BLDC Inverter motor, 90°C Steam Care hygiene cycle, 15-minute quick wash, and ultra-quiet operation.",
    shortDescription: "Front-load washer with BLDC Inverter motor and 90°C anti-allergy steam cycle.",
    price: 115000,
    oldPrice: 128000,
    discountPercentage: 10,
    stock: 7,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "8 KG", "Type": "Front Load Inverter", "Speed": "1400 RPM", "Steam": "90°C High Temp Steam Care" },
    features: ["Steam Care 99.9% Allergy Eradication", "BLDC Quiet Inverter Drive", "Lunar Dial Program Wheel"],
    warranty: "10 Years Inverter Motor Warranty",
    tags: ["Midea", "Front Load", "Steam Care", "Inverter"],
    isFeatured: true,
    isDeal: false,
    isNew: true,
    rating: 4.9,
    reviewCount: 19,
    weight: "63 kg",
    dimensions: "595 x 530 x 850 mm",
    color: "Graphite Gray",
    capacity: "8 KG",
    model: "MF100W80B",
    installationAvailable: true,
    deliveryAvailable: true
  },

  // 59-65: GEYSERS
  {
    name: "Nasgas Instant Geyser Super Flow 10L",
    slug: "nasgas-instant-geyser-super-flow-10l",
    brand: "Nasgas",
    category: "Geysers",
    subcategory: "Instant Gas Geysers",
    sku: "HC-GAS-001",
    description: "Nasgas Super Flow 10L instant gas geyser with pure oxygen-free copper heat exchanger, low-pressure water startup, electronic battery ignition, and winter/summer flame selector.",
    shortDescription: "Instantaneous 10L gas geyser with heavy copper heat exchanger and low-water pressure ignition.",
    price: 22000,
    oldPrice: 25000,
    discountPercentage: 12,
    stock: 20,
    stockStatus: "in_stock",
    images: [
      "https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=800&q=80"
    ],
    thumbnail: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "10 Liters/min", "Heat Exchanger": "100% Oxygen-Free Heavy Copper", "Gas Type": "Natural Gas (SNG) / LPG compatible", "Startup": "Low Water Pressure 0.02 Mpa" },
    features: ["Zero-Pressure Ignition for High Floor Apartments", "Winter/Summer Dual Burner Switch", "20-Minute Timer Cutoff Safety"],
    warranty: "1 Year Official Nasgas Warranty",
    tags: ["Nasgas", "Instant Geyser", "10L", "Gas Geyser"],
    isFeatured: true,
    isDeal: true,
    isNew: false,
    rating: 4.8,
    reviewCount: 34,
    weight: "9.2 kg",
    dimensions: "590 x 340 x 180 mm",
    color: "Gloss White & Gold",
    capacity: "10 Liters",
    model: "SF-10L",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Super Asia Instant Geyser Auto Ignition 8L",
    slug: "super-asia-instant-geyser-auto-ignition-8l",
    brand: "Super Asia",
    category: "Geysers",
    subcategory: "Instant Gas Geysers",
    sku: "HC-GAS-002",
    description: "Super Asia 8L automatic instant geyser delivers uninterrupted warm water with anti-freeze protection, flameout safety cut-off, and heavy brass water assembly.",
    shortDescription: "Reliable 8L instant geyser with flame failure safety valve and copper heat coil.",
    price: 19500,
    oldPrice: 22000,
    discountPercentage: 11,
    stock: 22,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "8 Liters/min", "Safety": "Flame Failure & Overheat Shutoff", "Body": "Powder Coated Rust Proof" },
    features: ["Automatic Battery Ignition", "Water Flow Adjustable Sensor", "Double Solenoid Gas Protection"],
    warranty: "1 Year Official Warranty",
    tags: ["Super Asia", "Instant Geyser", "8L"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.7,
    reviewCount: 22,
    weight: "8.1 kg",
    dimensions: "550 x 320 x 170 mm",
    color: "Off White",
    capacity: "8 Liters",
    model: "SA-8L-INST",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Canon Instant Geyser Ultra Fast 12L",
    slug: "canon-instant-geyser-ultra-fast-12l",
    brand: "Canon",
    category: "Geysers",
    subcategory: "Instant Gas Geysers",
    sku: "HC-GAS-003",
    description: "Canon 12L high-volume instant geyser engineered for multiple bathrooms or heavy flow rain showers with digital LED temperature display.",
    shortDescription: "High-volume 12L instant geyser with digital temperature readout for rain showers.",
    price: 24500,
    oldPrice: 28000,
    discountPercentage: 12,
    stock: 14,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "12 Liters/min High Flow", "Display": "Live Digital Water Temperature", "Ignition": "Dual Pulse Automatic" },
    features: ["Large 12L Capacity for Rain Showers", "Live Digital Water Temp Display", "Oxygen Depletion Protection Sensor"],
    warranty: "1 Year Canon Warranty",
    tags: ["Canon", "12L", "Instant Geyser", "Digital"],
    isFeatured: true,
    isDeal: false,
    isNew: true,
    rating: 4.8,
    reviewCount: 19,
    weight: "10.5 kg",
    dimensions: "640 x 360 x 190 mm",
    color: "Metallic Silver",
    capacity: "12 Liters",
    model: "C-12L-UF",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Fischer Geyser Storage Gas & Electric 35 Gallons",
    slug: "fischer-geyser-storage-gas-electric-35-gallons",
    brand: "Fischer",
    category: "Geysers",
    subcategory: "Storage Geysers",
    sku: "HC-GAS-004",
    description: "Fischer 35 Gallon dual gas and electric storage geyser with heavy galvanized iron boiler sheet, glass wool thermal insulation, and Italian safety thermostat.",
    shortDescription: "Commercial-grade 35 gallon storage geyser with dual gas and electric heating.",
    price: 49000,
    oldPrice: 55000,
    discountPercentage: 11,
    stock: 8,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "35 Gallons (132 Liters)", "Boiler Sheet": "10/12 Gauge Galvanized Iron", "Dual Heating": "Gas Burner + 2000W Electric Rod" },
    features: ["Thick High-Density Glass Wool Insulation", "Dual Fuel Operation (Gas & Electric)", "Italian Safety Thermostat Regulator"],
    warranty: "3 Years Tank Replacement Warranty",
    tags: ["Fischer", "35 Gallon", "Storage Geyser", "Dual Fuel"],
    isFeatured: true,
    isDeal: false,
    isNew: false,
    rating: 4.9,
    reviewCount: 26,
    weight: "48 kg",
    dimensions: "1300 x 480 x 480 mm",
    color: "Powder Coated Gray",
    capacity: "35 Gallons",
    model: "FG-35GE",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Midas Geyser Instant 6L Compact",
    slug: "midas-geyser-instant-6l-compact",
    brand: "Midas",
    category: "Geysers",
    subcategory: "Instant Gas Geysers",
    sku: "HC-GAS-005",
    description: "Midas 6L compact instant geyser designed for small bathrooms, kitchen sinks, and tight spaces with rapid heating and gas economy.",
    shortDescription: "Compact 6L instant geyser tailored for quick kitchen or single-bathroom hot water.",
    price: 17000,
    oldPrice: 19500,
    discountPercentage: 13,
    stock: 19,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "6 Liters/min", "Size": "Space-Saving Ultra Compact", "Coil": "Copper Heating Coil" },
    features: ["Economical Low Gas Consumption", "Compact Slim Fit Enclosure", "Automatic Dry-Burn Protection"],
    warranty: "1 Year Official Warranty",
    tags: ["Midas", "6L", "Compact Geyser"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.5,
    reviewCount: 15,
    weight: "6.8 kg",
    dimensions: "490 x 300 x 150 mm",
    color: "White",
    capacity: "6 Liters",
    model: "M-6L-COMP",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Golden Fuji Geyser Dual Storage 30 Gallon",
    slug: "golden-fuji-geyser-dual-storage-30-gallon",
    brand: "Golden Fuji",
    category: "Geysers",
    subcategory: "Storage Geysers",
    sku: "HC-GAS-006",
    description: "Golden Fuji 30 Gallon storage geyser crafted with heavy-gauge corrosion resistant boiler and energy efficient burner for continuous winter warmth.",
    shortDescription: "Heavy gauge 30 gallon storage geyser with high heat retention insulation.",
    price: 44000,
    oldPrice: 49000,
    discountPercentage: 10,
    stock: 10,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "30 Gallons", "Boiler": "Heavy Zinc Coated GI Sheet", "Type": "Dual Fuel Gas & Electric" },
    features: ["Rust-Resistant Internal Galvanizing", "Over-Temperature Pressure Relief Valve", "Heavy Duty Stand Mounting"],
    warranty: "2 Years Tank Warranty",
    tags: ["Golden Fuji", "30 Gallon", "Storage Geyser"],
    isFeatured: false,
    isDeal: false,
    isNew: false,
    rating: 4.6,
    reviewCount: 18,
    weight: "42 kg",
    dimensions: "1220 x 460 x 460 mm",
    color: "Hammered Gray",
    capacity: "30 Gallons",
    model: "GF-30G",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Glory Geyser Instant 10L Gold Series",
    slug: "glory-geyser-instant-10l-gold-series",
    brand: "Glory",
    category: "Geysers",
    subcategory: "Instant Gas Geysers",
    sku: "HC-GAS-007",
    description: "Glory Gold Series 10L instant geyser with copper heat exchanger, anti-dry combustion device, and winter booster burner configuration.",
    shortDescription: "10L instant gas geyser with copper exchanger and dual heat adjustment knobs.",
    price: 20500,
    oldPrice: 23000,
    discountPercentage: 11,
    stock: 17,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "10 Liters/min", "Ignition": "Instant Battery Pulse", "Heat Shield": "Pure Copper Core" },
    features: ["Anti-Dry Combustion Sensor", "Stable Flame Wind-Proof Flue Design", "Summer/Winter Gas Economy Dial"],
    warranty: "1 Year Official Warranty",
    tags: ["Glory", "10L", "Instant Geyser"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.6,
    reviewCount: 14,
    weight: "8.6 kg",
    dimensions: "580 x 330 x 175 mm",
    color: "Gold & White",
    capacity: "10 Liters",
    model: "GL-10-GOLD",
    installationAvailable: true,
    deliveryAvailable: true
  }
];
