import { SeedProduct } from './data';

export const PRODUCTS_PART_1: SeedProduct[] = [
  // 1-10: AIR CONDITIONERS
  {
    name: "Hyundai Inverter AC Smart HAC-13T3 Turbo Breeze 1.0 Ton",
    slug: "hyundai-inverter-ac-smart-hac-13t3-turbo-breeze-1-0-ton",
    brand: "Hyundai",
    category: "DC Inverter AC",
    subcategory: "1.0 Ton Inverter",
    sku: "HC-AC-001",
    description: "Hyundai Smart HAC-13T3 Turbo Breeze 1.0 Ton DC Inverter Air Conditioner features T3 compressor technology engineered for extreme ambient temperatures up to 55°C. Delivers 60% energy saving with rapid cooling.",
    shortDescription: "T3 Turbo Breeze 1.0 Ton Inverter AC with up to 60% electricity savings and Gold Fin anti-corrosion coating.",
    price: 138000,
    oldPrice: 152000,
    discountPercentage: 9,
    stock: 15,
    stockStatus: "in_stock",
    images: [
      "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80"
    ],
    thumbnail: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "1.0 Ton (12000 BTU)", "Compressor": "T3 Full DC Inverter", "Refrigerant": "R410A Eco Gas", "Energy Efficiency": "Up to 60% saving", "Warranty": "10 Years Compressor / 1 Year Parts" },
    features: ["T3 Tropicalized Inverter Compressor", "Turbo Breeze Rapid Cooling Mode", "Gold Fin Heat Exchanger", "Auto Clean & Self-Diagnosis"],
    warranty: "10 Years Compressor, 1 Year Parts Official Warranty",
    tags: ["Inverter AC", "Hyundai", "1 Ton", "T3 Compressor", "Energy Saver"],
    isFeatured: true,
    isDeal: true,
    isNew: false,
    rating: 4.8,
    reviewCount: 16,
    weight: "38 kg",
    dimensions: "840 x 280 x 205 mm",
    color: "Glossy White",
    capacity: "1.0 Ton",
    model: "HAC-13T3",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "TCL SaveIN-31S Smart Inverter AC TAC-18SVN-EX 1.5 Ton",
    slug: "tcl-savein-31s-smart-inverter-ac-tac-18svn-ex-1-5-ton",
    brand: "TCL",
    category: "DC Inverter AC",
    subcategory: "1.5 Ton Inverter",
    sku: "HC-AC-002",
    description: "TCL SaveIN-31S TAC-18SVN-EX delivers AI inverter smart cooling with WiFi remote connectivity, gentle breeze airflow, and self-cleaning technology.",
    shortDescription: "1.5 Ton Smart WiFi Inverter AC featuring Gentle Breeze Airflow and 66% Power Conservation.",
    price: 172000,
    oldPrice: 189000,
    discountPercentage: 9,
    stock: 12,
    stockStatus: "in_stock",
    images: [
      "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80"
    ],
    thumbnail: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "1.5 Ton (18000 BTU)", "WiFi": "Smart IoT App Control", "Compressor": "T3 Twin Rotary Inverter", "Warranty": "10 Years Compressor" },
    features: ["Smart WiFi IoT Connectivity", "Gentle Breeze Micro-Hole Vanes", "Deep Clean 55°C High Temp Sterilization"],
    warranty: "10 Years Compressor, 2 Years PCB, 1 Year Parts",
    tags: ["TCL", "1.5 Ton", "WiFi AC", "Smart AC"],
    isFeatured: true,
    isDeal: false,
    isNew: true,
    rating: 4.9,
    reviewCount: 22,
    weight: "44 kg",
    dimensions: "910 x 294 x 206 mm",
    color: "Arctic White",
    capacity: "1.5 Ton",
    model: "TAC-18SVN-EX",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Midea Eco T3 DC Inverter Smart AC 1.0 Ton",
    slug: "midea-eco-t3-dc-inverter-smart-ac-1-0-ton",
    brand: "Midea",
    category: "DC Inverter AC",
    subcategory: "1.0 Ton Inverter",
    sku: "HC-AC-003",
    description: "Midea Eco T3 DC Inverter AC provides high cooling capacity even in 60°C severe desert conditions with Golden Fin protection and gear shift power management.",
    shortDescription: "1.0 Ton Eco T3 high-ambient cooling inverter AC with gear shift energy saving.",
    price: 132000,
    oldPrice: 145000,
    discountPercentage: 9,
    stock: 10,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "1.0 Ton (12000 BTU)", "Type": "Heat & Cool Inverter", "Gas": "R32 Green Gas" },
    features: ["Gear Shift 50%/75%/100% Power Control", "High-Density Bio Filter", "Tropicalized T3 Outdoor"],
    warranty: "10 Years Compressor Warranty",
    tags: ["Midea", "1 Ton", "Eco Inverter"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.7,
    reviewCount: 14,
    weight: "36 kg",
    dimensions: "805 x 285 x 194 mm",
    color: "White",
    capacity: "1.0 Ton",
    model: "MST-12CRDN1",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "PEL Jumbo Prime Plus T3+ Inverter AC 1.5 Ton",
    slug: "pel-jumbo-prime-plus-t3-inverter-ac-1-5-ton",
    brand: "PEL",
    category: "DC Inverter AC",
    subcategory: "1.5 Ton Inverter",
    sku: "HC-AC-004",
    description: "PEL Jumbo Prime Plus T3+ 1.5 Ton Inverter AC with extra large indoor unit and jumbo outdoor condenser designed for fast drop in temperature during peak Pakistani heatwaves.",
    shortDescription: "Jumbo Indoor & Outdoor T3+ high ambient cooling up to 58°C with 4D airflow.",
    price: 168000,
    oldPrice: 184000,
    discountPercentage: 9,
    stock: 8,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "1.5 Ton (18000 BTU)", "Airflow": "4D Surround Air", "Compressor": "T3+ Super Inverter" },
    features: ["Full 100% Copper Piping", "A++ Energy Rating", "Golden Hydrophilic Fin"],
    warranty: "10 Years Compressor, 1 Year Parts",
    tags: ["PEL", "Jumbo", "1.5 Ton", "Prime Plus"],
    isFeatured: true,
    isDeal: false,
    isNew: false,
    rating: 4.8,
    reviewCount: 19,
    weight: "48 kg",
    dimensions: "990 x 315 x 220 mm",
    color: "Mirror Glass White",
    capacity: "1.5 Ton",
    model: "PINV-18K-JPP",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "American General T3 Heaven E-Smart 1.5 Ton",
    slug: "american-general-t3-heaven-e-smart-1-5-ton",
    brand: "American General",
    category: "DC Inverter AC",
    subcategory: "1.5 Ton Inverter",
    sku: "HC-AC-005",
    description: "American General T3 Heaven E-Smart 1.5 Ton DC Inverter delivers industrial strength heavy cooling with whisper quiet indoor sound levels.",
    shortDescription: "Commercial-grade T3 compressor for uncompromising performance in Lahore summers.",
    price: 178000,
    oldPrice: 195000,
    discountPercentage: 9,
    stock: 7,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "1.5 Ton (18000 BTU)", "Outdoor Type": "Heavy Duty T3 Condenser", "Voltage": "150V Low Voltage Startup" },
    features: ["Low Voltage Startup from 150V", "Anti-Fungus Self Clean", "Whisper Quiet 24dB Operation"],
    warranty: "10 Years Compressor Warranty",
    tags: ["American General", "Heavy Duty", "1.5 Ton"],
    isFeatured: false,
    isDeal: false,
    isNew: true,
    rating: 4.9,
    reviewCount: 11,
    weight: "46 kg",
    dimensions: "940 x 300 x 215 mm",
    color: "Gloss White",
    capacity: "1.5 Ton",
    model: "AG-18-HVN",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "PEL Cool Breeze 1.5 Ton Cool Only AC",
    slug: "pel-cool-breeze-1-5-ton-cool-only-ac",
    brand: "PEL",
    category: "DC Inverter AC",
    subcategory: "1.5 Ton Inverter",
    sku: "HC-AC-006",
    description: "PEL Cool Breeze 1.5 Ton Cool Only Air Conditioner provides cost-effective, high-output cooling without extra winter heating costs.",
    shortDescription: "Affordable and reliable 1.5 Ton cooling solution for budget-conscious families.",
    price: 155000,
    oldPrice: 168000,
    discountPercentage: 8,
    stock: 9,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "1.5 Ton (18000 BTU)", "Function": "Cooling Only", "Fin Type": "Blue Fin Anti-Corrosion" },
    features: ["Rapid Chill Mode", "Intelligent Sleep Curve", "High Efficiency Fin Coating"],
    warranty: "10 Years Compressor, 1 Year Parts",
    tags: ["PEL", "Cool Only", "1.5 Ton", "Affordable"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.6,
    reviewCount: 15,
    weight: "42 kg",
    dimensions: "900 x 290 x 205 mm",
    color: "White",
    capacity: "1.5 Ton",
    model: "PCB-18K-CO",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Orient EVO 19R T3 DC Inverter AC 1.5 Ton",
    slug: "orient-evo-19r-t3-dc-inverter-ac-1-5-ton",
    brand: "Orient",
    category: "DC Inverter AC",
    subcategory: "1.5 Ton Inverter",
    sku: "HC-AC-007",
    description: "Orient EVO 19R T3 DC Inverter comes equipped with Mewar smart chip, energy meter tracking, and full 50-feet long reach airflow.",
    shortDescription: "Smart energy tracker DC Inverter with 50ft long distance throw and T3 heat endurance.",
    price: 174000,
    oldPrice: 192000,
    discountPercentage: 9,
    stock: 11,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "1.5 Ton (18000 BTU)", "Air Throw": "50 Feet", "Smart App": "Orient Smart App Compatible" },
    features: ["Built-in Real Time Power Consumption Meter", "50ft Long Airflow", "100% Copper Tubing"],
    warranty: "10 Years Compressor, 1 Year PCB & Parts",
    tags: ["Orient", "EVO", "1.5 Ton", "Smart AC"],
    isFeatured: false,
    isDeal: false,
    isNew: true,
    rating: 4.7,
    reviewCount: 18,
    weight: "45 kg",
    dimensions: "920 x 305 x 210 mm",
    color: "Pearl White",
    capacity: "1.5 Ton",
    model: "EVO-19R-1.5T",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Hisense Split AC 12TV60 T3 1 Ton",
    slug: "hisense-split-ac-12tv60-t3-1-ton",
    brand: "Hisense",
    category: "DC Inverter AC",
    subcategory: "1.0 Ton Inverter",
    sku: "HC-AC-008",
    description: "Hisense 12TV60 T3 1 Ton Inverter features I-Feel temperature sensing in the remote control, fast cooling, and 4-sleep modes.",
    shortDescription: "1.0 Ton Split Inverter with I-Feel smart sensor and 4-way automated air louvers.",
    price: 135000,
    oldPrice: 148000,
    discountPercentage: 9,
    stock: 14,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "1.0 Ton (12000 BTU)", "Compressor": "T3 Rotary Inverter", "Eco Mode": "Yes" },
    features: ["I-Feel Temperature Sensing Remote", "Carbon Filter Air Purification", "Low Noise Design"],
    warranty: "10 Years Compressor, 1 Year Parts",
    tags: ["Hisense", "1 Ton", "Inverter AC"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.7,
    reviewCount: 13,
    weight: "37 kg",
    dimensions: "830 x 280 x 200 mm",
    color: "White",
    capacity: "1.0 Ton",
    model: "12TV60",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Haier Inverter AC 1.5 Ton HSU-18HNS",
    slug: "haier-inverter-ac-1-5-ton-hsu-18hns",
    brand: "Haier",
    category: "DC Inverter AC",
    subcategory: "1.5 Ton Inverter",
    sku: "HC-AC-009",
    description: "Haier 1.5 Ton UPS-Enabled Inverter AC operates seamlessly on solar and UPS power setups with One-Touch Self Clean sterilization.",
    shortDescription: "Pakistan's #1 Selling 1.5 Ton Inverter with UPS/Solar compatibility and One-Touch Cold Expansion Self Cleaning.",
    price: 179000,
    oldPrice: 198000,
    discountPercentage: 10,
    stock: 20,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "1.5 Ton (18000 BTU)", "UPS Enabled": "Runs on UPS / Solar", "Self Clean": "99.9% Sterilization Cold Expansion" },
    features: ["UPS Device Integration Support", "Cold Expansion Self Cleaning Tech", "Hyper PCB Protection 130V-260V"],
    warranty: "10 Years Compressor, 4 Years PCB, 1 Year Parts",
    tags: ["Haier", "1.5 Ton", "UPS AC", "Best Seller"],
    isFeatured: true,
    isDeal: true,
    isNew: false,
    rating: 4.9,
    reviewCount: 35,
    weight: "46 kg",
    dimensions: "930 x 310 x 220 mm",
    color: "Pure White",
    capacity: "1.5 Ton",
    model: "HSU-18HNS",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Gree Inverter AC 1.5 Ton Pular Series",
    slug: "gree-inverter-ac-1-5-ton-pular-series",
    brand: "Gree",
    category: "DC Inverter AC",
    subcategory: "1.5 Ton Inverter",
    sku: "HC-AC-010",
    description: "Gree Pular Series 1.5 Ton Inverter AC with G-10 Inverter engine, ultra-low frequency torque control, and matte finish European design.",
    shortDescription: "Gree G-10 Ultra High Efficiency Inverter with matte European styling and 3D airflow.",
    price: 188000,
    oldPrice: 205000,
    discountPercentage: 8,
    stock: 16,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "1.5 Ton (18000 BTU)", "Compressor": "Gree G-10 Inverter", "Airflow": "7 Fan Speed Settings" },
    features: ["G-10 High Torque Inverter Technology", "Seven Fan Speed Controls", "Hidden LED Temperature Display"],
    warranty: "10 Years Compressor, 1 Year Parts",
    tags: ["Gree", "Pular", "1.5 Ton", "Premium AC"],
    isFeatured: true,
    isDeal: false,
    isNew: true,
    rating: 4.9,
    reviewCount: 28,
    weight: "47 kg",
    dimensions: "950 x 310 x 215 mm",
    color: "Matte White",
    capacity: "1.5 Ton",
    model: "GS-18PITH",
    installationAvailable: true,
    deliveryAvailable: true
  },

  // 11-20: LED / QLED TVs
  {
    name: "TCL 32 Inch QLED Smart Google TV 32S51K",
    slug: "tcl-32-inch-qled-smart-google-tv-32s51k",
    brand: "TCL",
    category: "LED & QLED TVs",
    subcategory: "32 Inch TV",
    sku: "HC-TV-001",
    description: "TCL 32S51K brings Quantum Dot QLED technology to the 32-inch category with over a billion colors, official Google TV OS, Dolby Audio, and bezel-less metallic frame.",
    shortDescription: "True Quantum Dot QLED display in 32-inch with Google TV, Chromecast, and HDR10.",
    price: 52000,
    oldPrice: 58000,
    discountPercentage: 10,
    stock: 18,
    stockStatus: "in_stock",
    images: [
      "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1461151304267-38535e780c79?auto=format&fit=crop&w=800&q=80"
    ],
    thumbnail: "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80",
    specifications: { "Screen Size": "32 Inch", "Display": "QLED Quantum Dot", "OS": "Official Google TV", "Sound": "Dolby Audio 16W", "Connectivity": "WiFi, Bluetooth 5.0, 2x HDMI, USB" },
    features: ["1 Billion+ Vibrant QLED Colors", "Official Google TV with Play Store", "Built-in Google Assistant & Chromecast", "Frameless Metallic Design"],
    warranty: "2 Years Official TCL Pakistan Panel & Parts Warranty",
    tags: ["TCL", "32 Inch", "QLED", "Google TV", "Smart TV"],
    isFeatured: true,
    isDeal: true,
    isNew: true,
    rating: 4.8,
    reviewCount: 30,
    weight: "4.2 kg",
    dimensions: "715 x 425 x 80 mm",
    color: "Gunmetal Gray",
    capacity: "32 Inch",
    model: "32S51K",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Xiaomi 32A2026 32 Inch Google TV",
    slug: "xiaomi-32a2026-32-inch-google-tv",
    brand: "Xiaomi",
    category: "LED & QLED TVs",
    subcategory: "32 Inch TV",
    sku: "HC-TV-002",
    description: "Xiaomi 32A2026 32-inch Smart Google TV with Vivid Picture Engine, DTS-HD sound, premium bezel-less finish, and Bluetooth 360-degree voice remote.",
    shortDescription: "Ultra-slim 32-inch Google TV with Vivid Picture Engine and DTS-HD sound.",
    price: 49000,
    oldPrice: 55000,
    discountPercentage: 11,
    stock: 14,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80",
    specifications: { "Screen Size": "32 Inch HD", "OS": "Google TV Android 11", "Audio": "2x 10W DTS-Virtual:X", "Processor": "Quad-core A55" },
    features: ["Vivid Picture Engine Tuning", "360° Bluetooth Voice Remote", "PatchWall Content Hub"],
    warranty: "1 Year Official Brand Warranty",
    tags: ["Xiaomi", "32 Inch", "Smart TV", "Google TV"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.7,
    reviewCount: 20,
    weight: "3.9 kg",
    dimensions: "716 x 423 x 79 mm",
    color: "Black",
    capacity: "32 Inch",
    model: "L32M8-AFME",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "TCL 43 Inch Smart Google TV 43P635 4K",
    slug: "tcl-43-inch-smart-google-tv-43p635-4k",
    brand: "TCL",
    category: "LED & QLED TVs",
    subcategory: "43 Inch TV",
    sku: "HC-TV-003",
    description: "TCL 43P635 features crisp 4K Ultra HD resolution, HDR10 dynamic color enhancement, and hands-free voice control powered by Google TV.",
    shortDescription: "43-inch 4K HDR10 Google TV with Edgeless design and Dolby Audio surround.",
    price: 88000,
    oldPrice: 97000,
    discountPercentage: 9,
    stock: 12,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80",
    specifications: { "Screen Size": "43 Inch", "Resolution": "3840 x 2160 4K UHD", "HDR": "HDR10 & HLG", "OS": "Google TV" },
    features: ["4K UHD Clarity with AiPQ Engine", "Dynamic Color Enhancer", "Edgeless Minimalist Bezel"],
    warranty: "2 Years Official TCL Warranty",
    tags: ["TCL", "43 Inch", "4K TV", "Google TV"],
    isFeatured: true,
    isDeal: false,
    isNew: false,
    rating: 4.8,
    reviewCount: 24,
    weight: "7.1 kg",
    dimensions: "958 x 556 x 78 mm",
    color: "Titanium Black",
    capacity: "43 Inch",
    model: "43P635",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "TCL 55 Inch QLED Smart TV 55C645 4K",
    slug: "tcl-55-inch-qled-smart-tv-55c645-4k",
    brand: "TCL",
    category: "LED & QLED TVs",
    subcategory: "55 Inch TV",
    sku: "HC-TV-004",
    description: "TCL 55C645 4K QLED Smart TV with 120Hz Game Accelerator, Dolby Vision & Atmos, AMD FreeSync, and 450-nit peak brightness.",
    shortDescription: "55-inch 4K QLED Gaming TV with 120Hz DLG, Dolby Vision Atmos and ONKYO Sound.",
    price: 154000,
    oldPrice: 172000,
    discountPercentage: 10,
    stock: 9,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80",
    specifications: { "Screen Size": "55 Inch", "Panel": "Quantum Dot QLED", "Refresh Rate": "120Hz DLG Game Mode", "Audio": "Dolby Atmos / DTS-HD" },
    features: ["Quantum Dot Color Purity", "120Hz DLG Game Accelerator", "Dolby Vision Cinema Experience"],
    warranty: "2 Years TCL Official Warranty",
    tags: ["TCL", "55 Inch", "QLED", "120Hz", "Dolby Vision"],
    isFeatured: true,
    isDeal: true,
    isNew: true,
    rating: 4.9,
    reviewCount: 29,
    weight: "12.3 kg",
    dimensions: "1225 x 711 x 81 mm",
    color: "Metallic Silver",
    capacity: "55 Inch",
    model: "55C645",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Haier 43 Inch Smart LED TV H43K66UG",
    slug: "haier-43-inch-smart-led-tv-h43k66ug",
    brand: "Haier",
    category: "LED & QLED TVs",
    subcategory: "43 Inch TV",
    sku: "HC-TV-005",
    description: "Haier H43K66UG 43-inch Bezel-less 4K Android TV with Google Assistant voice search, HQ sound, and certified Netflix and YouTube 4K streaming.",
    shortDescription: "43-inch Bezel-less 4K Android TV with licensed apps and surround audio.",
    price: 84000,
    oldPrice: 93000,
    discountPercentage: 10,
    stock: 11,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80",
    specifications: { "Screen Size": "43 Inch", "Resolution": "3840 x 2160", "OS": "Android 11 Licensed", "Sound": "24W Stereo Speakers" },
    features: ["Zero-Bezel Design", "Google Chromecast Built-in", "Auto Low Latency Mode"],
    warranty: "2 Years Panel, 1 Year Parts Warranty",
    tags: ["Haier", "43 Inch", "Android TV"],
    isFeatured: false,
    isDeal: false,
    isNew: false,
    rating: 4.7,
    reviewCount: 16,
    weight: "7.0 kg",
    dimensions: "960 x 560 x 80 mm",
    color: "Black",
    capacity: "43 Inch",
    model: "H43K66UG",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Hisense 43 Inch Smart LED TV 43A6K",
    slug: "hisense-43-inch-smart-led-tv-43a6k",
    brand: "Hisense",
    category: "LED & QLED TVs",
    subcategory: "43 Inch TV",
    sku: "HC-TV-006",
    description: "Hisense 43A6K 4K Google TV features Dolby Vision, DTS Virtual:X sound, Sports Mode, and Game Mode PLUS for lag-free entertainment.",
    shortDescription: "43-inch 4K Google TV with Dolby Vision and dedicated Sports Smooth Motion mode.",
    price: 86000,
    oldPrice: 95000,
    discountPercentage: 9,
    stock: 10,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80",
    specifications: { "Screen Size": "43 Inch", "Display": "4K Ultra HD Direct LED", "OS": "Google TV", "HDR": "Dolby Vision, HDR10" },
    features: ["Dolby Vision HDR Cinema", "AI Smooth Sports Mode", "Voice Remote with Google Assistant"],
    warranty: "2 Years Brand Warranty",
    tags: ["Hisense", "43 Inch", "4K", "Dolby Vision"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.7,
    reviewCount: 14,
    weight: "6.9 kg",
    dimensions: "963 x 560 x 74 mm",
    color: "Black",
    capacity: "43 Inch",
    model: "43A6K",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Samsung Smart LED TV 43CU7000 Crystal UHD 4K",
    slug: "samsung-smart-led-tv-43cu7000-crystal-uhd-4k",
    brand: "Samsung",
    category: "LED & QLED TVs",
    subcategory: "43 Inch TV",
    sku: "HC-TV-007",
    description: "Samsung 43CU7000 Crystal UHD 4K Smart TV powered by Crystal Processor 4K, PurColor true-to-life tones, and Tizen OS with Samsung SmartThings hub.",
    shortDescription: "Premium Samsung Crystal 4K Processor with PurColor and Q-Symphony sound.",
    price: 112000,
    oldPrice: 125000,
    discountPercentage: 10,
    stock: 8,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80",
    specifications: { "Screen Size": "43 Inch", "Processor": "Crystal Processor 4K", "OS": "Tizen Smart TV", "Audio": "Q-Symphony 20W" },
    features: ["PurColor Life-like Colors", "Crystal Processor 4K Upscaling", "SmartThings Smart Home Integration"],
    warranty: "1 Year Official Samsung Pakistan Warranty",
    tags: ["Samsung", "Crystal UHD", "43 Inch", "4K"],
    isFeatured: true,
    isDeal: false,
    isNew: false,
    rating: 4.9,
    reviewCount: 31,
    weight: "8.1 kg",
    dimensions: "963 x 558 x 60 mm",
    color: "Titan Gray",
    capacity: "43 Inch",
    model: "UA43CU7000",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Skyworth Smart LED TV 40E20 40 Inch",
    slug: "skyworth-smart-led-tv-40e20-40-inch",
    brand: "Skyworth",
    category: "LED & QLED TVs",
    subcategory: "40 Inch TV",
    sku: "HC-TV-008",
    description: "Skyworth 40E20 40-inch Full HD Smart Android TV with Trochilus Extreme picture engine and Boundless 4.0 ultra-thin screen framing.",
    shortDescription: "40-inch FHD Frameless Smart TV with Android OS and Dolby Audio.",
    price: 64000,
    oldPrice: 72000,
    discountPercentage: 11,
    stock: 13,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80",
    specifications: { "Screen Size": "40 Inch", "Resolution": "1920 x 1080 Full HD", "OS": "Android TV", "Sound": "20W Box Speakers" },
    features: ["Boundless 4.0 Screen Design", "Trochilus Picture Engine", "Eye-Care Flicker Free"],
    warranty: "2 Years Brand Warranty",
    tags: ["Skyworth", "40 Inch", "Smart TV"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.6,
    reviewCount: 12,
    weight: "5.8 kg",
    dimensions: "892 x 515 x 75 mm",
    color: "Black",
    capacity: "40 Inch",
    model: "40E20",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Infinix Smart TV 43X5 Full HD Android",
    slug: "infinix-smart-tv-43x5-full-hd-android",
    brand: "Infinix",
    category: "LED & QLED TVs",
    subcategory: "43 Inch TV",
    sku: "HC-TV-009",
    description: "Infinix 43X5 43-inch Frameless Android TV with EPIC 2.0 Picture Engine, 24W box speakers, and blue-light eye protection certification.",
    shortDescription: "Vibrant 43-inch Android Smart TV engineered for movies and gaming enthusiasts.",
    price: 68000,
    oldPrice: 76000,
    discountPercentage: 11,
    stock: 15,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80",
    specifications: { "Screen Size": "43 Inch", "Resolution": "1920 x 1080 FHD", "OS": "Android 11", "Audio": "24W Box Speakers" },
    features: ["EPIC 2.0 Image Processing", "Full Bezel-less Aesthetic", "TUV Rheinland Low Blue Light"],
    warranty: "1 Year Official Warranty",
    tags: ["Infinix", "43 Inch", "Smart TV"],
    isFeatured: false,
    isDeal: false,
    isNew: true,
    rating: 4.6,
    reviewCount: 15,
    weight: "6.7 kg",
    dimensions: "960 x 555 x 76 mm",
    color: "Black",
    capacity: "43 Inch",
    model: "43X5",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Ecostar Smart LED TV 32 Inch CX-32U571",
    slug: "ecostar-smart-led-tv-32-inch-cx-32u571",
    brand: "Ecostar",
    category: "LED & QLED TVs",
    subcategory: "32 Inch TV",
    sku: "HC-TV-010",
    description: "Ecostar CX-32U571 32-inch Smart LED TV with built-in licensed applications, high-contrast IPS grade panel, and USB multimedia playback.",
    shortDescription: "Economical 32-inch smart television with wide viewing angle panel and clear acoustics.",
    price: 44000,
    oldPrice: 49000,
    discountPercentage: 10,
    stock: 16,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80",
    specifications: { "Screen Size": "32 Inch", "Panel Type": "A+ Grade IPS", "Connectivity": "2 HDMI, 2 USB, WiFi" },
    features: ["High Dynamic Contrast", "Nature View Color Calibration", "Surround Sound Presets"],
    warranty: "2 Years Panel Warranty",
    tags: ["Ecostar", "32 Inch", "Budget TV"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.5,
    reviewCount: 18,
    weight: "4.1 kg",
    dimensions: "720 x 425 x 78 mm",
    color: "Black",
    capacity: "32 Inch",
    model: "CX-32U571",
    installationAvailable: true,
    deliveryAvailable: true
  },

  // 21-28: REFRIGERATORS
  {
    name: "Haier HRF-246 IP Smart Inverter Refrigerator",
    slug: "haier-hrf-246-ip-smart-inverter-refrigerator",
    brand: "Haier",
    category: "Refrigerators",
    subcategory: "9 CFT Refrigerator",
    sku: "HC-REF-001",
    description: "Haier HRF-246 IP 9 Cubic Feet Smart Inverter Refrigerator features 1-hour fast ice making, 105V low-voltage operation, and digital inverter energy reduction.",
    shortDescription: "9 Cu. Ft. Digital Inverter Refrigerator with 1-hour ice making and 10-year compressor warranty.",
    price: 94000,
    oldPrice: 104000,
    discountPercentage: 10,
    stock: 14,
    stockStatus: "in_stock",
    images: [
      "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80"
    ],
    thumbnail: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "9 Cu. Ft. (246 Liters)", "Compressor": "Smart Inverter", "Voltage": "105V - 260V Stabilizer Free", "Refrigerant": "R600a Eco Gas" },
    features: ["1 Hour Icing Technology", "Runs on Solar / UPS", "T-Frost Thick Insulation", "Food Grade Interior"],
    warranty: "10 Years Compressor, 1 Year Parts Official Haier Warranty",
    tags: ["Haier", "Refrigerator", "Inverter", "9 CFT"],
    isFeatured: true,
    isDeal: true,
    isNew: false,
    rating: 4.8,
    reviewCount: 26,
    weight: "52 kg",
    dimensions: "1350 x 550 x 560 mm",
    color: "Inox Silver",
    capacity: "9 Cu. Ft.",
    model: "HRF-246-IP",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Kenwood KRF-22257 New Persona Plus Series 9 CFT Refrigerator",
    slug: "kenwood-krf-22257-new-persona-plus-series-9-cft-refrigerator",
    brand: "Kenwood",
    category: "Refrigerators",
    subcategory: "9 CFT Refrigerator",
    sku: "HC-REF-002",
    description: "Kenwood Persona Plus KRF-22257 features artistic glass door finish, SECOP German technology compressor, and antibacterial gasket.",
    shortDescription: "Designer Glass Door 9 CFT Refrigerator with German engineered SECOP compressor.",
    price: 98000,
    oldPrice: 108000,
    discountPercentage: 9,
    stock: 10,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "9 Cu. Ft.", "Door Finish": "Tempered Mirror Glass", "Compressor": "SECOP European Tech" },
    features: ["Scratch-Resistant Glass Door", "Removable Anti-Fungal Gasket", "Heavy Duty Wire Racks"],
    warranty: "10 Years Compressor Warranty",
    tags: ["Kenwood", "Persona Plus", "Glass Door", "9 CFT"],
    isFeatured: false,
    isDeal: false,
    isNew: true,
    rating: 4.7,
    reviewCount: 15,
    weight: "54 kg",
    dimensions: "1370 x 560 x 580 mm",
    color: "Midnight Black Glass",
    capacity: "9 Cu. Ft.",
    model: "KRF-22257",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Haier HRF-346 IAPA+ Digital Inverter Refrigerator 12 CFT",
    slug: "haier-hrf-346-iapa-digital-inverter-refrigerator-12-cft",
    brand: "Haier",
    category: "Refrigerators",
    subcategory: "12 CFT Refrigerator",
    sku: "HC-REF-003",
    description: "Haier HRF-346 IAPA+ 12 Cu. Ft. Digital Inverter Refrigerator with A.SPE fresh air sterilization, 4-in-1 convertible temperature zones, and digital touch control.",
    shortDescription: "12 Cu. Ft. Large Family Digital Inverter with A.SPE sterilization and digital display.",
    price: 122000,
    oldPrice: 135000,
    discountPercentage: 10,
    stock: 12,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "12 Cu. Ft. (346 Liters)", "Control": "External Digital Touch Panel", "Inverter": "2nd Gen Digital Inverter" },
    features: ["A.SPE Fresh Sterilization Module", "Exterior Digital Temperature Touch Panel", "Turbo Freezing Zone"],
    warranty: "10 Years Compressor, 1 Year Parts",
    tags: ["Haier", "12 CFT", "Digital Inverter", "Touch Panel"],
    isFeatured: true,
    isDeal: true,
    isNew: false,
    rating: 4.9,
    reviewCount: 28,
    weight: "64 kg",
    dimensions: "1575 x 620 x 630 mm",
    color: "Titanium Inox",
    capacity: "12 Cu. Ft.",
    model: "HRF-346-IAPA+",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Dawlance Inverter Refrigerator 91996 Chrome Pro 14 CFT",
    slug: "dawlance-inverter-refrigerator-91996-chrome-pro-14-cft",
    brand: "Dawlance",
    category: "Refrigerators",
    subcategory: "14 CFT Refrigerator",
    sku: "HC-REF-004",
    description: "Dawlance 91996 Chrome Pro features Nature Lock Technology preserving vegetable vitamins for up to 20 days, and 55% less energy consumption.",
    shortDescription: "14 Cu. Ft. Nature Lock Inverter Refrigerator keeping greens crisp up to 20 days.",
    price: 136000,
    oldPrice: 149000,
    discountPercentage: 9,
    stock: 9,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "14 Cu. Ft.", "Technology": "Nature Lock Vegetable Box", "Warranty": "12 Years Compressor" },
    features: ["Nature Lock Humidity Balance", "55% Energy Saving Inverter", "Side by Side Air Cooling"],
    warranty: "12 Years Inverter Compressor Warranty",
    tags: ["Dawlance", "Chrome Pro", "14 CFT", "Nature Lock"],
    isFeatured: true,
    isDeal: false,
    isNew: true,
    rating: 4.8,
    reviewCount: 22,
    weight: "68 kg",
    dimensions: "1630 x 660 x 640 mm",
    color: "Chrome Hairline Stainless",
    capacity: "14 Cu. Ft.",
    model: "91996-Chrome-Pro",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "PEL Inverter Refrigerator PRIL-22250 11 CFT",
    slug: "pel-inverter-refrigerator-pril-22250-11-cft",
    brand: "PEL",
    category: "Refrigerators",
    subcategory: "11 CFT Refrigerator",
    sku: "HC-REF-005",
    description: "PEL PRIL-22250 Life Series 11 CFT Inverter Refrigerator with rapid cooling, instant ice trays, and Thicker Insulation for load-shedding protection.",
    shortDescription: "11 CFT Heavy Insulation Refrigerator built to sustain up to 10 hours cooling during power outages.",
    price: 104000,
    oldPrice: 115000,
    discountPercentage: 10,
    stock: 11,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "11 Cu. Ft.", "Insulation": "Thick Cell Polyurethane", "Gas": "R600a Pure" },
    features: ["10 Hours Cool Retention", "Crisp Humidity Slider", "Copper Condenser Coil"],
    warranty: "10 Years Compressor Warranty",
    tags: ["PEL", "Life Series", "11 CFT"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.7,
    reviewCount: 17,
    weight: "58 kg",
    dimensions: "1490 x 590 x 600 mm",
    color: "Silver Metallic",
    capacity: "11 Cu. Ft.",
    model: "PRIL-22250",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Kenwood Inverter Refrigerator Glass Mirror 12 CFT",
    slug: "kenwood-inverter-refrigerator-glass-mirror-12-cft",
    brand: "Kenwood",
    category: "Refrigerators",
    subcategory: "12 CFT Refrigerator",
    sku: "HC-REF-006",
    description: "Kenwood Mirror Series 12 CFT Glass Refrigerator featuring luxury mirror reflective finish and high COP efficiency compressor.",
    shortDescription: "Luxury Full Mirror Glass Finish 12 CFT Refrigerator with LED tower interior lights.",
    price: 126000,
    oldPrice: 139000,
    discountPercentage: 9,
    stock: 8,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "12 Cu. Ft.", "Finish": "Reflective Mirror Toughened Glass", "Lighting": "Vertical Tower LED" },
    features: ["Edge to Edge Glass Design", "Deodorizing Carbon Matrix", "Heavy Load Tempered Shelves"],
    warranty: "10 Years Compressor Warranty",
    tags: ["Kenwood", "Mirror Glass", "12 CFT"],
    isFeatured: false,
    isDeal: false,
    isNew: true,
    rating: 4.8,
    reviewCount: 14,
    weight: "65 kg",
    dimensions: "1580 x 620 x 630 mm",
    color: "Smoked Mirror Glass",
    capacity: "12 Cu. Ft.",
    model: "KRF-24457",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Homage Refrigerator HR-243 9 CFT",
    slug: "homage-refrigerator-hr-243-9-cft",
    brand: "Homage",
    category: "Refrigerators",
    subcategory: "9 CFT Refrigerator",
    sku: "HC-REF-007",
    description: "Homage HR-243 9 CFT Refrigerator engineered for efficient everyday household cooling with silent compressor and rapid defrost system.",
    shortDescription: "Reliable 9 CFT refrigerator with low noise operation and quick cooling action.",
    price: 88000,
    oldPrice: 97000,
    discountPercentage: 9,
    stock: 12,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "9 Cu. Ft.", "Condenser": "External Steel Wire", "Noise": "Under 38 dB" },
    features: ["Spacious Freezer Compartment", "Adjustable Leveling Legs", "Eco Friendly Gas"],
    warranty: "10 Years Compressor Warranty",
    tags: ["Homage", "9 CFT", "Refrigerator"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.5,
    reviewCount: 11,
    weight: "51 kg",
    dimensions: "1340 x 550 x 560 mm",
    color: "Charcoal Gray",
    capacity: "9 Cu. Ft.",
    model: "HR-243",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Electrolux Refrigerator Frost-Free Multi-Flow 15 CFT",
    slug: "electrolux-refrigerator-frost-free-multi-flow-15-cft",
    brand: "Electrolux",
    category: "Refrigerators",
    subcategory: "15 CFT Refrigerator",
    sku: "HC-REF-008",
    description: "Electrolux 15 CFT No-Frost Multi-Flow Refrigerator with Scandinavian temperature uniformity, TasteLock crisper, and inverter compressor.",
    shortDescription: "Premium 15 CFT No-Frost Refrigerator with TasteLock vegetable crisper and Multi-Flow vents.",
    price: 185000,
    oldPrice: 205000,
    discountPercentage: 10,
    stock: 6,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80",
    specifications: { "Capacity": "15 Cu. Ft.", "Defrosting": "100% Frost Free No Ice Buildup", "Airflow": "360 Multi Air Flow" },
    features: ["No Frost Defrost Technology", "TasteLock Freshness Chamber", "Dual Evaporator System"],
    warranty: "10 Years Compressor Warranty",
    tags: ["Electrolux", "No Frost", "15 CFT", "Premium"],
    isFeatured: true,
    isDeal: false,
    isNew: true,
    rating: 4.9,
    reviewCount: 19,
    weight: "74 kg",
    dimensions: "1720 x 700 x 680 mm",
    color: "Stainless Steel Inox",
    capacity: "15 Cu. Ft.",
    model: "ETB-4600",
    installationAvailable: false,
    deliveryAvailable: true
  },

  // 29-36: WATER DISPENSERS / COOLERS
  {
    name: "Dawlance 1051 Champagne Glass Door Water Dispenser",
    slug: "dawlance-1051-champagne-glass-door-water-dispenser",
    brand: "Dawlance",
    category: "Water Dispensers",
    subcategory: "Glass Door Dispenser",
    sku: "HC-WD-001",
    description: "Dawlance 1051 Champagne features 3-tap hot, cold and room temperature water with bottom refrigerator cabinet, tempered champagne glass door, and child safety lock.",
    shortDescription: "Elegant Champagne Glass Door 3-tap Water Dispenser with 20L mini refrigerator compartment.",
    price: 43000,
    oldPrice: 48000,
    discountPercentage: 10,
    stock: 14,
    stockStatus: "in_stock",
    images: [
      "https://images.unsplash.com/photo-1546554137-f86b9593a222?auto=format&fit=crop&w=800&q=80"
    ],
    thumbnail: "https://images.unsplash.com/photo-1546554137-f86b9593a222?auto=format&fit=crop&w=800&q=80",
    specifications: { "Taps": "3 (Hot, Cold, Normal)", "Cabinet": "20 Liter Mini Refrigerator", "Compressor": "Danfoss High Performance" },
    features: ["Child Safety Lock for Hot Water", "Stainless Steel Anti-Bacterial Water Tank", "Designer Glass Front Door"],
    warranty: "3 Years Compressor, 1 Year Parts",
    tags: ["Dawlance", "Water Dispenser", "Champagne", "3 Tap"],
    isFeatured: true,
    isDeal: true,
    isNew: false,
    rating: 4.8,
    reviewCount: 22,
    weight: "21 kg",
    dimensions: "1020 x 360 x 380 mm",
    color: "Champagne Gold Glass",
    capacity: "3 Taps + 20L Cabinet",
    model: "WD-1051-CH",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Dawlance 1051 Beige Red Glass Door Water Dispenser",
    slug: "dawlance-1051-beige-red-glass-door-water-dispenser",
    brand: "Dawlance",
    category: "Water Dispensers",
    subcategory: "Glass Door Dispenser",
    sku: "HC-WD-002",
    description: "Dawlance 1051 Beige Red Glass edition combines rich wine-red tones with champagne trims, 3 stainless steel water tanks, and swift chilling performance.",
    shortDescription: "Luxury Beige Red designer glass water dispenser with rapid cooling and mini fridge.",
    price: 43000,
    oldPrice: 48000,
    discountPercentage: 10,
    stock: 11,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1546554137-f86b9593a222?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1546554137-f86b9593a222?auto=format&fit=crop&w=800&q=80",
    specifications: { "Taps": "3 Taps", "Capacity Cold": "4 Liters/Hour", "Capacity Hot": "5 Liters/Hour" },
    features: ["Luxury Beige Red Tempered Glass", "Low Power Eco Heating System", "Removable Drip Tray"],
    warranty: "3 Years Compressor Warranty",
    tags: ["Dawlance", "Beige Red", "Water Dispenser"],
    isFeatured: false,
    isDeal: false,
    isNew: true,
    rating: 4.7,
    reviewCount: 16,
    weight: "21 kg",
    dimensions: "1020 x 360 x 380 mm",
    color: "Beige Red Glass",
    capacity: "3 Taps + 20L Cabinet",
    model: "WD-1051-BR",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "PEL PWD 315 Smart Water Dispenser",
    slug: "pel-pwd-315-smart-water-dispenser",
    brand: "PEL",
    category: "Water Dispensers",
    subcategory: "Glass Door Dispenser",
    sku: "HC-WD-003",
    description: "PEL PWD 315 features energy-efficient cooling compressor, 3 push-button taps, bottom storage refrigerator, and anti-leak bottle collar.",
    shortDescription: "PEL 3-tap water dispenser with spacious cooling cabinet and food-grade stainless tank.",
    price: 39000,
    oldPrice: 44000,
    discountPercentage: 11,
    stock: 15,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1546554137-f86b9593a222?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1546554137-f86b9593a222?auto=format&fit=crop&w=800&q=80",
    specifications: { "Taps": "3 Push Taps", "Tank": "SS304 Food Grade Stainless Steel", "Cooling Type": "Compressor Cooling" },
    features: ["Food Grade Hygienic Tank", "Convenient Push Faucets", "Built-in Lower Refrigerator"],
    warranty: "3 Years Compressor Warranty",
    tags: ["PEL", "PWD 315", "Water Dispenser"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.6,
    reviewCount: 18,
    weight: "20 kg",
    dimensions: "1000 x 350 x 370 mm",
    color: "Black & Silver",
    capacity: "3 Taps",
    model: "PWD-315",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Midea YL-2037S-B Top Load Water Dispenser",
    slug: "midea-yl-2037s-b-top-load-water-dispenser",
    brand: "Midea",
    category: "Water Dispensers",
    subcategory: "Top Load Dispenser",
    sku: "HC-WD-004",
    description: "Midea YL-2037S-B is a compact and durable top load water dispenser providing ice-chilled and boiling hot water with high efficiency Danfoss cooling core.",
    shortDescription: "High-efficiency top load water dispenser with child safety protection.",
    price: 38000,
    oldPrice: 42000,
    discountPercentage: 10,
    stock: 12,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1546554137-f86b9593a222?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1546554137-f86b9593a222?auto=format&fit=crop&w=800&q=80",
    specifications: { "Type": "Top Load 3-Tap", "Compressor": "High Efficiency Danfoss Grade", "Warranty": "3 Years Compressor" },
    features: ["Overheat Safety Shutoff", "Quiet Running Compressor", "Compact Minimalist Footprint"],
    warranty: "3 Years Compressor Warranty",
    tags: ["Midea", "Top Load", "Water Dispenser"],
    isFeatured: false,
    isDeal: false,
    isNew: true,
    rating: 4.7,
    reviewCount: 13,
    weight: "18 kg",
    dimensions: "990 x 340 x 360 mm",
    color: "Black",
    capacity: "3 Taps",
    model: "YL-2037S-B",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Fischer FE 25 S.S Slim Electric Water Cooler",
    slug: "fischer-fe-25-s-s-slim-electric-water-cooler",
    brand: "Fischer",
    category: "Water Dispensers",
    subcategory: "Electric Water Cooler",
    sku: "HC-WD-005",
    description: "Fischer FE 25 stainless steel heavy-duty slim electric water cooler designed for offices, commercial institutions, and large residential spaces with continuous cold water.",
    shortDescription: "Heavy duty non-magnetic stainless steel commercial 25-liter electric water cooler.",
    price: 54000,
    oldPrice: 59000,
    discountPercentage: 8,
    stock: 10,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1546554137-f86b9593a222?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1546554137-f86b9593a222?auto=format&fit=crop&w=800&q=80",
    specifications: { "Tank Capacity": "25 Liters Cold Water", "Material": "Non-Magnetic Food Grade Stainless Steel", "Taps": "2 Heavy Brass Faucets" },
    features: ["Non-Magnetic Stainless Steel Body", "Heavy Duty Pure Copper Cooling Coil", "Thermostat Temperature Regulator"],
    warranty: "1 Year Official Fischer Warranty",
    tags: ["Fischer", "Stainless Steel", "Electric Cooler", "Commercial"],
    isFeatured: true,
    isDeal: false,
    isNew: false,
    rating: 4.9,
    reviewCount: 20,
    weight: "28 kg",
    dimensions: "1200 x 420 x 420 mm",
    color: "Brushed Stainless Steel",
    capacity: "25 Liters",
    model: "FE-25-SS",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Super Asia Water Dispenser Heavy Duty 3 Tap",
    slug: "super-asia-water-dispenser-heavy-duty-3-tap",
    brand: "Super Asia",
    category: "Water Dispensers",
    subcategory: "Glass Door Dispenser",
    sku: "HC-WD-006",
    description: "Super Asia 3-tap water dispenser with tempered glass front, extra-large cold water reservoir, and lower cooling cabinet.",
    shortDescription: "Rugged build 3-tap water dispenser with heavy refrigerator compartment.",
    price: 38500,
    oldPrice: 43000,
    discountPercentage: 10,
    stock: 13,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1546554137-f86b9593a222?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1546554137-f86b9593a222?auto=format&fit=crop&w=800&q=80",
    specifications: { "Taps": "3 Taps", "Capacity": "Extra Chill High Flow", "Refrigerant": "R134a" },
    features: ["High Capacity Cooling Reservoir", "Shock-Proof Electrical Components", "Removable Spill Grid"],
    warranty: "3 Years Compressor Warranty",
    tags: ["Super Asia", "Water Dispenser", "Durable"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.6,
    reviewCount: 15,
    weight: "20.5 kg",
    dimensions: "1010 x 355 x 375 mm",
    color: "Black & Red",
    capacity: "3 Taps",
    model: "SA-WD300",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Gree Water Dispenser Luxury Series",
    slug: "gree-water-dispenser-luxury-series",
    brand: "Gree",
    category: "Water Dispensers",
    subcategory: "Glass Door Dispenser",
    sku: "HC-WD-007",
    description: "Gree Luxury Series water dispenser features touch-sensitive faucets, whisper-quiet compressor, and tempered glass fascia.",
    shortDescription: "Ultra-quiet compressor water dispenser with elegant minimalist styling.",
    price: 44000,
    oldPrice: 49000,
    discountPercentage: 10,
    stock: 8,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1546554137-f86b9593a222?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1546554137-f86b9593a222?auto=format&fit=crop&w=800&q=80",
    specifications: { "Taps": "3 Taps", "Compressor": "Gree In-House High COP", "Safety": "Child Safety Hot Tap" },
    features: ["Whisper Quiet Vibration-Free Core", "High Chilling Recovery Speed", "Double Overheat Cutout"],
    warranty: "3 Years Compressor Warranty",
    tags: ["Gree", "Luxury", "Water Dispenser"],
    isFeatured: false,
    isDeal: false,
    isNew: true,
    rating: 4.8,
    reviewCount: 14,
    weight: "22 kg",
    dimensions: "1030 x 360 x 380 mm",
    color: "Titanium Silver",
    capacity: "3 Taps",
    model: "GWD-300L",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Canon Water Dispenser Classic 3 Tap",
    slug: "canon-water-dispenser-classic-3-tap",
    brand: "Canon",
    category: "Water Dispensers",
    subcategory: "Glass Door Dispenser",
    sku: "HC-WD-008",
    description: "Canon Classic 3-tap water dispenser provides dependable hot and cold refreshment with stainless steel reservoirs and bottom cooler storage.",
    shortDescription: "Value-packed 3-tap dispenser with durable parts and dependable compressor.",
    price: 36000,
    oldPrice: 40000,
    discountPercentage: 10,
    stock: 16,
    stockStatus: "in_stock",
    images: ["https://images.unsplash.com/photo-1546554137-f86b9593a222?auto=format&fit=crop&w=800&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1546554137-f86b9593a222?auto=format&fit=crop&w=800&q=80",
    specifications: { "Taps": "3 Taps", "Tanks": "Twin Stainless Steel", "Storage": "Mini Refrigerator" },
    features: ["Quick Dispense Spigots", "Easy Clean Removable Tray", "Energy Efficient Thermostat"],
    warranty: "3 Years Compressor Warranty",
    tags: ["Canon", "Classic", "Water Dispenser"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.5,
    reviewCount: 12,
    weight: "19.5 kg",
    dimensions: "995 x 345 x 365 mm",
    color: "Silver Grey",
    capacity: "3 Taps",
    model: "CWD-100",
    installationAvailable: false,
    deliveryAvailable: true
  }
];
