import { SeedProduct } from './data';

export const PRODUCTS_PART_3: SeedProduct[] = [
  // 66-75: AIR COOLERS & PURIFIERS
  {
    name: "Super Asia Air Cooler ECM-5000 Plus",
    slug: "super-asia-air-cooler-ecm-5000-plus",
    brand: "Super Asia",
    category: "Air Coolers",
    subcategory: "Desert Coolers",
    sku: "HC-ACLR-001",
    description: "Super Asia ECM-5000 Plus heavy-duty desert cooler with 70-liter water tank, imported pure cellulose honeycomb cooling pads, large ice chamber, and pure copper motor.",
    shortDescription: "70L Desert Air Cooler with 3-sided thick honeycomb cooling pads and ice compartment.",
    price: 33000,
    oldPrice: 37000,
    discountPercentage: 11,
    stock: 20,
    stockStatus: "in_stock",
    images: [
      "/images/products/super-asia-air-cooler-ecm-5000-plus.svg"
    ],
    thumbnail: "/images/products/super-asia-air-cooler-ecm-5000-plus.svg",
    specifications: { "Water Tank": "70 Liters", "Cooling Media": "3-Sided High Density Honeycomb Pads", "Fan": "Aerodynamic Powerful Fan Blade" },
    features: ["Top Ice Chamber for Instant Chill", "Heavy Duty Pure Copper Motor", "Caster Wheels for Easy Mobility"],
    warranty: "1 Year Official Warranty",
    tags: ["Super Asia", "Air Cooler", "Desert Cooler", "70L"],
    isFeatured: true,
    isDeal: true,
    isNew: false,
    rating: 4.8,
    reviewCount: 30,
    weight: "17 kg",
    dimensions: "680 x 510 x 1150 mm",
    color: "White & Blue",
    capacity: "70 Liters",
    model: "ECM-5000-Plus",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Boss Air Cooler ECM-7000 Jumbo",
    slug: "boss-air-cooler-ecm-7000-jumbo",
    brand: "Boss",
    category: "Air Coolers",
    subcategory: "Desert Coolers",
    sku: "HC-ACLR-002",
    description: "Boss ECM-7000 Jumbo room air cooler featuring immense 90-liter water tank, heavy air throw distance, and low noise aerofoil fan.",
    shortDescription: "90-Liter Jumbo Desert Air Cooler designed for spacious halls and living rooms.",
    price: 36500,
    oldPrice: 41000,
    discountPercentage: 11,
    stock: 15,
    stockStatus: "in_stock",
    images: [
      "/images/products/boss-air-cooler-ecm-7000-jumbo.svg"
    ],
    thumbnail: "/images/products/boss-air-cooler-ecm-7000-jumbo.svg",
    specifications: { "Water Tank": "90 Liters Jumbo", "Air Throw": "45 Feet Long Air Throw", "Power": "180W Low Electricity Usage" },
    features: ["Continuous Water Inlet Connection", "Triple Thick Honeycomb Cooling Matrix", "Multi-Directional Louvers"],
    warranty: "1 Year Motor Warranty",
    tags: ["Boss", "Air Cooler", "Jumbo", "90L"],
    isFeatured: false,
    isDeal: false,
    isNew: true,
    rating: 4.7,
    reviewCount: 21,
    weight: "19 kg",
    dimensions: "720 x 540 x 1230 mm",
    color: "White & Grey",
    capacity: "90 Liters",
    model: "ECM-7000",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Canon Air Cooler Storm 60L",
    slug: "canon-air-cooler-storm-60l",
    brand: "Canon",
    category: "Air Coolers",
    subcategory: "Desert Coolers",
    sku: "HC-ACLR-003",
    description: "Canon Storm 60L air cooler engineered with dual water distribution pipes, high-volume blower, and insect screen.",
    shortDescription: "60L Air Cooler with dual water distribution and insect mesh.",
    price: 31000,
    oldPrice: 35000,
    discountPercentage: 11,
    stock: 16,
    stockStatus: "in_stock",
    images: [
      "/images/products/canon-air-cooler-storm-60l.svg"
    ],
    thumbnail: "/images/products/canon-air-cooler-storm-60l.svg",
    specifications: { "Capacity": "60 Liters", "Motor": "100% Copper Winding", "Inverter Friendly": "Yes, runs on UPS/Solar" },
    features: ["Inverter Friendly Low Power Consumption", "Dust & Mosquito Protective Net", "Turbo Air Throw"],
    warranty: "1 Year Official Warranty",
    tags: ["Canon", "Air Cooler", "60L"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.6,
    reviewCount: 16,
    weight: "15.5 kg",
    dimensions: "650 x 480 x 1080 mm",
    color: "White & Green",
    capacity: "60 Liters",
    model: "C-STORM-60",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Nasgas Air Cooler NAC-9000 Turbo",
    slug: "nasgas-air-cooler-nac-9000-turbo",
    brand: "Nasgas",
    category: "Air Coolers",
    subcategory: "Desert Coolers",
    sku: "HC-ACLR-004",
    description: "Nasgas NAC-9000 Turbo air cooler built with shock-proof ABS polymer body, oversized ice box, and ultra-durable submersible water pump.",
    shortDescription: "Premium ABS polymer air cooler with oversized ice tray and high efficiency pump.",
    price: 34500,
    oldPrice: 38500,
    discountPercentage: 10,
    stock: 14,
    stockStatus: "in_stock",
    images: [
      "/images/products/nasgas-air-cooler-nac-9000-turbo.svg"
    ],
    thumbnail: "/images/products/nasgas-air-cooler-nac-9000-turbo.svg",
    specifications: { "Capacity": "75 Liters", "Material": "Virgin High Impact ABS", "Pump": "Heavy Duty Submersible" },
    features: ["Double Sized Ice Compartment", "Long Throw Aerodynamic Louvers", "Pure Copper Motor"],
    warranty: "1 Year Nasgas Warranty",
    tags: ["Nasgas", "Air Cooler", "Turbo"],
    isFeatured: false,
    isDeal: false,
    isNew: false,
    rating: 4.7,
    reviewCount: 18,
    weight: "17.5 kg",
    dimensions: "690 x 520 x 1180 mm",
    color: "White & Charcoal",
    capacity: "75 Liters",
    model: "NAC-9000",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Pakfans Air Cooler PF-700 Heavy Metal",
    slug: "pakfans-air-cooler-pf-700-heavy-metal",
    brand: "Pakfans",
    category: "Air Coolers",
    subcategory: "Metal Body Coolers",
    sku: "HC-ACLR-005",
    description: "Pakfans PF-700 traditional heavy metal galvanized body air cooler with legendary Pakfans industrial motor and rust-inhibiting coating.",
    shortDescription: "Ultra-rugged metal body desert cooler with high-durability Pakfans industrial motor.",
    price: 29500,
    oldPrice: 33000,
    discountPercentage: 11,
    stock: 12,
    stockStatus: "in_stock",
    images: [
      "/images/products/pakfans-air-cooler-pf-700-heavy-metal.svg"
    ],
    thumbnail: "/images/products/pakfans-air-cooler-pf-700-heavy-metal.svg",
    specifications: { "Body": "Galvanized Heavy Steel Sheet", "Motor": "Pakfans 100% Pure Copper", "Water Tank": "65 Liters" },
    features: ["Heavy Gauge Galvanized Sheet", "Legendary Pakfans Copper Motor", "High Velocity Steel Fan Blades"],
    warranty: "2 Years Motor Warranty",
    tags: ["Pakfans", "Metal Cooler", "Heavy Duty"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.6,
    reviewCount: 24,
    weight: "22 kg",
    dimensions: "700 x 600 x 1100 mm",
    color: "Hammered Silver Finish",
    capacity: "65 Liters",
    model: "PF-700",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Royal Air Cooler Deluxe Model 55L",
    slug: "royal-air-cooler-deluxe-model-55l",
    brand: "Royal",
    category: "Air Coolers",
    subcategory: "Room Coolers",
    sku: "HC-ACLR-006",
    description: "Royal Deluxe 55L air cooler designed for bedrooms and personal rooms with silent 3-speed fan and anti-clog water pump.",
    shortDescription: "Quiet bedroom room cooler with multi-directional motorized swing louvers.",
    price: 27000,
    oldPrice: 30000,
    discountPercentage: 10,
    stock: 15,
    stockStatus: "in_stock",
    images: [
      "/images/products/royal-air-cooler-deluxe-model-55l.svg"
    ],
    thumbnail: "/images/products/royal-air-cooler-deluxe-model-55l.svg",
    specifications: { "Capacity": "55 Liters", "Noise": "Low Noise Night Mode", "Swing": "Motorized Auto Oscillation" },
    features: ["Motorized Oscillating Air Vanes", "Low Sound Output for Bedrooms", "Compact Footprint"],
    warranty: "1 Year Official Warranty",
    tags: ["Royal", "Deluxe", "Room Cooler"],
    isFeatured: false,
    isDeal: false,
    isNew: false,
    rating: 4.5,
    reviewCount: 14,
    weight: "14 kg",
    dimensions: "620 x 450 x 1020 mm",
    color: "Off White",
    capacity: "55 Liters",
    model: "R-DLX-55",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Xiaomi Air Purifier Smart 4 Pro",
    slug: "xiaomi-air-purifier-smart-4-pro",
    brand: "Xiaomi",
    category: "Air Purifiers",
    subcategory: "HEPA Air Purifiers",
    sku: "HC-PUR-001",
    description: "Xiaomi Smart Air Purifier 4 Pro with high-efficiency 3-in-1 filtration eliminating 99.97% of particles down to 0.3 microns, OLED touch display, PM2.5/PM10 dual sensors, and Mi Home app control to combat Lahore smog.",
    shortDescription: "Lahore Smog Essential: High-output CADR 500m3/h HEPA air purifier with laser particle sensors.",
    price: 74000,
    oldPrice: 82000,
    discountPercentage: 10,
    stock: 16,
    stockStatus: "in_stock",
    images: [
      "/images/products/xiaomi-air-purifier-smart-4-pro.svg"
    ],
    thumbnail: "/images/products/xiaomi-air-purifier-smart-4-pro.svg",
    specifications: { "CADR": "500 m3/h Clean Air", "Filter": "High-Efficiency 3-in-1 HEPA + Activated Carbon", "Coverage": "Up to 60 m2 Room", "Noise": "33.7 dB Whisper Quiet" },
    features: ["Real-Time PM2.5 Air Quality OLED Indicator", "Negative Air Ionization for Forest Freshness", "Mi Home & Google Assistant Integration"],
    warranty: "1 Year Official Xiaomi Pakistan Warranty",
    tags: ["Xiaomi", "Air Purifier", "Smog", "HEPA", "Smart"],
    isFeatured: true,
    isDeal: true,
    isNew: true,
    rating: 4.9,
    reviewCount: 42,
    weight: "6.8 kg",
    dimensions: "275 x 275 x 680 mm",
    color: "Matte White",
    capacity: "60 m2 Coverage",
    model: "AC-M15-SC",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Philips Air Purifier Series 1000i",
    slug: "philips-air-purifier-series-1000i",
    brand: "Philips",
    category: "Air Purifiers",
    subcategory: "HEPA Air Purifiers",
    sku: "HC-PUR-002",
    description: "Philips Series 1000i intelligent air purifier equipped with NanoProtect HEPA filter capturing 99.97% of ultra-fine pollutants, AeraSense real-time air feedback, and smart app scheduling.",
    shortDescription: "NanoProtect HEPA filtration with color-coded live AeraSense air quality ring.",
    price: 68000,
    oldPrice: 75000,
    discountPercentage: 9,
    stock: 11,
    stockStatus: "in_stock",
    images: [
      "/images/products/philips-air-purifier-series-1000i.svg"
    ],
    thumbnail: "/images/products/philips-air-purifier-series-1000i.svg",
    specifications: { "Filter": "NanoProtect HEPA + Active Carbon", "CADR": "300 m3/h", "Sensor": "AeraSense Professional Grade" },
    features: ["Color Coded Air Quality Ring", "Quiet Sleep Mode with Dimmed Lights", "Removes Allergens, Viruses and Smoke"],
    warranty: "2 Years Worldwide Philips Warranty",
    tags: ["Philips", "Air Purifier", "NanoProtect"],
    isFeatured: false,
    isDeal: false,
    isNew: false,
    rating: 4.8,
    reviewCount: 20,
    weight: "5.8 kg",
    dimensions: "273 x 273 x 486 mm",
    color: "White & Grey",
    capacity: "40 m2",
    model: "AC1215/20",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "GFC Air Purifier Pure Air 400",
    slug: "gfc-air-purifier-pure-air-400",
    brand: "GFC",
    category: "Air Purifiers",
    subcategory: "HEPA Air Purifiers",
    sku: "HC-PUR-003",
    description: "GFC Pure Air 400 engineered with multi-stage HEPA filter and carbon matrix specifically calibrated to purify fine particulate matter in Pakistani urban environments.",
    shortDescription: "Heavy-duty HEPA air purifier with carbon deodorizer and digital air indicator.",
    price: 48000,
    oldPrice: 53000,
    discountPercentage: 9,
    stock: 14,
    stockStatus: "in_stock",
    images: [
      "/images/products/gfc-air-purifier-pure-air-400.svg"
    ],
    thumbnail: "/images/products/gfc-air-purifier-pure-air-400.svg",
    specifications: { "CADR": "380 m3/h", "Filtration": "True HEPA H13 Grade", "Timer": "1-8 Hours Timer" },
    features: ["True HEPA H13 Filtration", "VOC & Chemical Odor Reduction", "Filter Replacement Reminder"],
    warranty: "1 Year Official GFC Warranty",
    tags: ["GFC", "Air Purifier", "H13 HEPA"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.7,
    reviewCount: 16,
    weight: "6.2 kg",
    dimensions: "310 x 310 x 590 mm",
    color: "White",
    capacity: "45 m2",
    model: "PA-400",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Super Asia Air Purifier SAP-200 Smog Shield",
    slug: "super-asia-air-purifier-sap-200-smog-shield",
    brand: "Super Asia",
    category: "Air Purifiers",
    subcategory: "HEPA Air Purifiers",
    sku: "HC-PUR-004",
    description: "Super Asia SAP-200 Smog Shield compact room air purifier with medical grade filtration, low power 45W motor, and silent sleep settings.",
    shortDescription: "Compact and powerful room air purifier with multi-layer anti-smog filtration.",
    price: 38000,
    oldPrice: 42000,
    discountPercentage: 10,
    stock: 18,
    stockStatus: "in_stock",
    images: [
      "/images/products/super-asia-air-purifier-sap-200-smog-shield.svg"
    ],
    thumbnail: "/images/products/super-asia-air-purifier-sap-200-smog-shield.svg",
    specifications: { "Filtration": "Medical Grade H13 HEPA", "Power": "45W Low Consumption", "Noise": "28 dB in Sleep Mode" },
    features: ["Child Lock Safety Function", "Activated Carbon Sponge", "Ultra Quiet Night Operation"],
    warranty: "1 Year Official Warranty",
    tags: ["Super Asia", "Smog Shield", "Air Purifier"],
    isFeatured: false,
    isDeal: true,
    isNew: true,
    rating: 4.6,
    reviewCount: 15,
    weight: "4.8 kg",
    dimensions: "260 x 260 x 470 mm",
    color: "Pure White",
    capacity: "30 m2",
    model: "SAP-200",
    installationAvailable: false,
    deliveryAvailable: true
  },

  // 76-79: VACUUM CLEANERS
  {
    name: "Panasonic Vacuum Cleaner MC-CG713 2000W Drum",
    slug: "panasonic-vacuum-cleaner-mc-cg713-2000w-drum",
    brand: "Panasonic",
    category: "Vacuum Cleaners",
    subcategory: "Drum Vacuums",
    sku: "HC-VAC-001",
    description: "Panasonic MC-CG713 2000W high-power heavy duty drum vacuum cleaner with 18-liter dust capacity, blower function, tough metallic body, and Japanese craftsmanship.",
    shortDescription: "Heavy-duty 2000W 18L metal drum vacuum cleaner with blower function.",
    price: 38000,
    oldPrice: 42000,
    discountPercentage: 10,
    stock: 14,
    stockStatus: "in_stock",
    images: [
      "/images/products/panasonic-vacuum-cleaner-mc-cg713-2000w-drum.svg"
    ],
    thumbnail: "/images/products/panasonic-vacuum-cleaner-mc-cg713-2000w-drum.svg",
    specifications: { "Power": "2000W Input", "Dust Capacity": "18 Liters Metal Drum", "Functions": "Suction & High Velocity Blower", "Cord": "8 Meter Long Cord" },
    features: ["Built-in Blower Function for Lawns and Patios", "Durable Steel Drum Construction", "Anti-Bacteria Exhaust Filter"],
    warranty: "1 Year Official Panasonic Warranty",
    tags: ["Panasonic", "Vacuum Cleaner", "2000W", "Drum"],
    isFeatured: true,
    isDeal: false,
    isNew: false,
    rating: 4.9,
    reviewCount: 27,
    weight: "7.8 kg",
    dimensions: "360 x 360 x 540 mm",
    color: "Metallic Red & Black",
    capacity: "18 Liters",
    model: "MC-CG713",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Kenwood Vacuum Cleaner VBP80 2200W",
    slug: "kenwood-vacuum-cleaner-vbp80-2200w",
    brand: "Kenwood",
    category: "Vacuum Cleaners",
    subcategory: "Drum Vacuums",
    sku: "HC-VAC-002",
    description: "Kenwood VBP80 2200W drum vacuum cleaner with massive 25-liter capacity, washable cloth dust filter, telescopic metal wand, and heavy carpet nozzle.",
    shortDescription: "2200W extreme suction 25L drum vacuum cleaner with metal telescopic tube.",
    price: 41000,
    oldPrice: 46000,
    discountPercentage: 11,
    stock: 12,
    stockStatus: "in_stock",
    images: [
      "/images/products/kenwood-vacuum-cleaner-vbp80-2200w.svg"
    ],
    thumbnail: "/images/products/kenwood-vacuum-cleaner-vbp80-2200w.svg",
    specifications: { "Power": "2200W Max Suction", "Capacity": "25 Liters Large Drum", "Filter": "Washable Heavy Cloth Filter" },
    features: ["Massive 25-Liter Dust Storage", "Telescopic Steel Extension Tube", "Crevice & Upholstery Attachments"],
    warranty: "1 Year Kenwood Official Warranty",
    tags: ["Kenwood", "Vacuum", "2200W", "25L"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.8,
    reviewCount: 19,
    weight: "8.5 kg",
    dimensions: "380 x 380 x 580 mm",
    color: "Silver & Orange",
    capacity: "25 Liters",
    model: "VBP80",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "WestPoint Vacuum Cleaner WF-932 Wet & Dry",
    slug: "westpoint-vacuum-cleaner-wf-932-wet-dry",
    brand: "WestPoint",
    category: "Vacuum Cleaners",
    subcategory: "Wet & Dry Vacuums",
    sku: "HC-VAC-003",
    description: "WestPoint WF-932 versatile wet & dry vacuum cleaner capable of picking up liquid spills, broken glass, dust, and gravel with equal ease.",
    shortDescription: "Dual action wet & dry 1800W vacuum cleaner for versatile cleaning tasks.",
    price: 28000,
    oldPrice: 31500,
    discountPercentage: 11,
    stock: 16,
    stockStatus: "in_stock",
    images: [
      "/images/products/westpoint-vacuum-cleaner-wf-932-wet-dry.svg"
    ],
    thumbnail: "/images/products/westpoint-vacuum-cleaner-wf-932-wet-dry.svg",
    specifications: { "Type": "Wet and Dry Cleaning", "Power": "1800W", "Tank": "20 Liter Heavy Plastic Reservoir" },
    features: ["Liquid Spill Extraction Capacity", "Blower Port for Clearing Dust", "Overfill Float Safety Valve"],
    warranty: "2 Years Official Warranty",
    tags: ["WestPoint", "Wet Dry", "Vacuum"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.7,
    reviewCount: 22,
    weight: "6.9 kg",
    dimensions: "350 x 350 x 510 mm",
    color: "Blue & Black",
    capacity: "20 Liters",
    model: "WF-932",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Hitachi Vacuum Cleaner CV-950Y 2100W",
    slug: "hitachi-vacuum-cleaner-cv-950y-2100w",
    brand: "Hitachi",
    category: "Vacuum Cleaners",
    subcategory: "Drum Vacuums",
    sku: "HC-VAC-004",
    description: "Hitachi CV-950Y legendary Japanese engineered 2100W heavy duty drum vacuum cleaner with 18L capacity, dust disposal handle, and cloth filter.",
    shortDescription: "Japanese Hitachi 2100W high-durability drum vacuum with dust disposal handle.",
    price: 43000,
    oldPrice: 48000,
    discountPercentage: 10,
    stock: 10,
    stockStatus: "in_stock",
    images: [
      "/images/products/hitachi-vacuum-cleaner-cv-950y-2100w.svg"
    ],
    thumbnail: "/images/products/hitachi-vacuum-cleaner-cv-950y-2100w.svg",
    specifications: { "Motor": "2100W High Motor Life", "Origin": "Made in Thailand (Hitachi Japan Tech)", "Drum": "Solid Metal Body" },
    features: ["Convenient Dust Disposal Handle", "Rugged Steel Casing", "Blower Functionality"],
    warranty: "1 Year Official Warranty",
    tags: ["Hitachi", "2100W", "Japanese Tech", "Vacuum"],
    isFeatured: true,
    isDeal: false,
    isNew: true,
    rating: 4.9,
    reviewCount: 23,
    weight: "8.1 kg",
    dimensions: "370 x 370 x 550 mm",
    color: "Platinum Grey",
    capacity: "18 Liters",
    model: "CV-950Y",
    installationAvailable: false,
    deliveryAvailable: true
  },

  // 80-82: LAPTOPS
  {
    name: "Dell Inspiron 15 3520 Core i5 12th Gen",
    slug: "dell-inspiron-15-3520-core-i5-12th-gen",
    brand: "Dell",
    category: "Laptops",
    subcategory: "Core i5 Laptops",
    sku: "HC-LAP-001",
    description: "Dell Inspiron 15 3520 featuring 12th Gen Intel Core i5-1235U processor (10 cores, 12 threads), 8GB DDR4 RAM, 512GB NVMe SSD, 15.6-inch FHD 120Hz anti-glare display, and Windows 11 Home.",
    shortDescription: "15.6-inch 120Hz FHD Core i5 12th Gen business and student laptop with 512GB NVMe SSD.",
    price: 158000,
    oldPrice: 172000,
    discountPercentage: 8,
    stock: 10,
    stockStatus: "in_stock",
    images: [
      "/images/products/dell-inspiron-15-3520-core-i5-12th-gen.svg"
    ],
    thumbnail: "/images/products/dell-inspiron-15-3520-core-i5-12th-gen.svg",
    specifications: { "Processor": "Intel Core i5-1235U (Up to 4.4 GHz)", "RAM": "8GB DDR4 (Upgradable)", "Storage": "512GB PCIe NVMe SSD", "Display": "15.6 Inch FHD 120Hz IPS" },
    features: ["Smooth 120Hz Refresh Rate Display", "ExpressCharge 80% in 60 mins", "Lift Hinge for Ergonomic Typing"],
    warranty: "1 Year Official Dell Warranty",
    tags: ["Dell", "Inspiron", "Core i5", "Laptop"],
    isFeatured: true,
    isDeal: false,
    isNew: false,
    rating: 4.8,
    reviewCount: 19,
    weight: "1.65 kg",
    dimensions: "358 x 235 x 18 mm",
    color: "Carbon Black",
    capacity: "8GB / 512GB",
    model: "Inspiron-3520",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "HP 15s-fq5000 Core i5 12th Gen",
    slug: "hp-15s-fq5000-core-i5-12th-gen",
    brand: "HP",
    category: "Laptops",
    subcategory: "Core i5 Laptops",
    sku: "HC-LAP-002",
    description: "HP 15s sleek laptop with Intel Core i5-1235U, 8GB RAM, 512GB SSD, micro-edge 15.6 FHD IPS screen, fast charging, and backlit keyboard.",
    shortDescription: "Sleek Natural Silver Core i5 12th Gen laptop with micro-edge FHD screen and long battery life.",
    price: 162000,
    oldPrice: 178000,
    discountPercentage: 9,
    stock: 9,
    stockStatus: "in_stock",
    images: [
      "/images/products/hp-15s-fq5000-core-i5-12th-gen.svg"
    ],
    thumbnail: "/images/products/hp-15s-fq5000-core-i5-12th-gen.svg",
    specifications: { "Processor": "Intel Core i5-1235U", "Memory": "8GB DDR4-3200", "Storage": "512GB NVMe M.2 SSD", "Battery": "Up to 7.5 Hours" },
    features: ["Micro-Edge Bezel Display", "HP Fast Charge Technology", "Dual Array Digital Microphones"],
    warranty: "1 Year HP Official Warranty",
    tags: ["HP", "15s", "Core i5", "Silver"],
    isFeatured: true,
    isDeal: true,
    isNew: false,
    rating: 4.8,
    reviewCount: 22,
    weight: "1.69 kg",
    dimensions: "358 x 242 x 17.9 mm",
    color: "Natural Silver",
    capacity: "8GB / 512GB",
    model: "15s-fq5000",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Lenovo IdeaPad 3 Core i7 12th Gen 16GB",
    slug: "lenovo-ideapad-3-core-i7-12th-gen-16gb",
    brand: "Lenovo",
    category: "Laptops",
    subcategory: "Core i7 Laptops",
    sku: "HC-LAP-003",
    description: "Lenovo IdeaPad 3 powered by Intel Core i7-1255U (10 cores), 16GB RAM, 512GB Gen 4 NVMe SSD, Dolby Audio, and privacy shutter webcam.",
    shortDescription: "High-performance Core i7 12th Gen with 16GB RAM for multitasking and heavy workloads.",
    price: 215000,
    oldPrice: 235000,
    discountPercentage: 9,
    stock: 7,
    stockStatus: "in_stock",
    images: [
      "/images/products/lenovo-ideapad-3-core-i7-12th-gen-16gb.svg"
    ],
    thumbnail: "/images/products/lenovo-ideapad-3-core-i7-12th-gen-16gb.svg",
    specifications: { "CPU": "Intel Core i7-1255U (Up to 4.7 GHz)", "RAM": "16GB Dual Channel DDR4", "Storage": "512GB PCIe 4.0 SSD", "Sound": "Dolby Audio Stereo" },
    features: ["Physical Webcam Privacy Shutter", "Lenovo Eye Care Display Mode", "Intelligent Thermal Cooling Profiles"],
    warranty: "1 Year Lenovo Warranty",
    tags: ["Lenovo", "IdeaPad", "Core i7", "16GB RAM"],
    isFeatured: true,
    isDeal: false,
    isNew: true,
    rating: 4.9,
    reviewCount: 16,
    weight: "1.63 kg",
    dimensions: "359 x 236 x 19.9 mm",
    color: "Arctic Grey",
    capacity: "16GB / 512GB",
    model: "IdeaPad-3-15IAU7",
    installationAvailable: false,
    deliveryAvailable: true
  },

  // 83-89: MOBILES
  {
    name: "Samsung Galaxy A55 5G 8GB/256GB",
    slug: "samsung-galaxy-a55-5g-8gb-256gb",
    brand: "Samsung",
    category: "Mobiles",
    subcategory: "5G Smartphones",
    sku: "HC-MOB-001",
    description: "Samsung Galaxy A55 5G PTA-approved smartphone with premium metal frame, Super AMOLED 120Hz display, 50MP OIS camera, Exynos 1480, and IP67 water resistance.",
    shortDescription: "Official PTA-approved Galaxy A55 5G with metal frame, 120Hz Super AMOLED, and IP67 water proofing.",
    price: 139000,
    oldPrice: 149000,
    discountPercentage: 7,
    stock: 15,
    stockStatus: "in_stock",
    images: [
      "/images/products/samsung-galaxy-a55-5g-8gb-256gb.svg"
    ],
    thumbnail: "/images/products/samsung-galaxy-a55-5g-8gb-256gb.svg",
    specifications: { "PTA Status": "Official PTA Approved", "Display": "6.6 Inch Super AMOLED 120Hz HDR10+", "Camera": "50MP Main with OIS + 12MP Ultra-wide + 5MP Macro", "Battery": "5000 mAh with 25W Fast Charge" },
    features: ["IP67 Dust & Water Resistance", "Corning Gorilla Glass Victus+ Front & Back", "4 Generations of OS Updates"],
    warranty: "1 Year Official Samsung Pakistan Warranty",
    tags: ["Samsung", "Galaxy A55", "5G", "PTA Approved", "A-Series"],
    isFeatured: true,
    isDeal: false,
    isNew: true,
    rating: 4.9,
    reviewCount: 38,
    weight: "213 g",
    dimensions: "161.1 x 77.4 x 8.2 mm",
    color: "Awesome Iceblue",
    capacity: "8GB RAM / 256GB ROM",
    model: "SM-A556B",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Oppo Reno 11F 5G 8GB/256GB",
    slug: "oppo-reno-11f-5g-8gb-256gb",
    brand: "Oppo",
    category: "Mobiles",
    subcategory: "5G Smartphones",
    sku: "HC-MOB-002",
    description: "Oppo Reno 11F 5G with magnetic particle design, 64MP Ultra-Clear Triple Camera, 67W SUPERVOOC flash charge, and borderless 120Hz AMOLED display.",
    shortDescription: "Ultra-slim portrait expert smartphone with 67W fast charging and 64MP camera.",
    price: 79999,
    oldPrice: 87000,
    discountPercentage: 8,
    stock: 16,
    stockStatus: "in_stock",
    images: [
      "/images/products/oppo-reno-11f-5g-8gb-256gb.svg"
    ],
    thumbnail: "/images/products/oppo-reno-11f-5g-8gb-256gb.svg",
    specifications: { "PTA Status": "Official PTA Approved", "Charging": "67W SUPERVOOC Flash Charge", "Display": "6.7 Inch 120Hz Borderless AMOLED" },
    features: ["67W Rapid Battery Charge in 48 mins", "Ultra-Volume 300% Mode", "IP65 Water and Dust Resistance"],
    warranty: "1 Year Official Oppo Warranty",
    tags: ["Oppo", "Reno 11F", "5G", "SUPERVOOC"],
    isFeatured: true,
    isDeal: true,
    isNew: false,
    rating: 4.8,
    reviewCount: 25,
    weight: "177 g",
    dimensions: "161.6 x 74.7 x 7.5 mm",
    color: "Palm Green",
    capacity: "8GB / 256GB",
    model: "CPH2603",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Vivo V30e 5G 8GB/256GB Studio Quality Aura Light",
    slug: "vivo-v30e-5g-8gb-256gb-studio-quality-aura-light",
    brand: "Vivo",
    category: "Mobiles",
    subcategory: "5G Smartphones",
    sku: "HC-MOB-003",
    description: "Vivo V30e 5G with Studio Quality Aura Light portrait photography, Sony IMX882 sensor, 5500 mAh battery, and 3D curved 120Hz AMOLED screen.",
    shortDescription: "Studio Aura Light portrait camera phone with 5500mAh massive battery in an ultra-slim body.",
    price: 89999,
    oldPrice: 97000,
    discountPercentage: 7,
    stock: 12,
    stockStatus: "in_stock",
    images: [
      "/images/products/vivo-v30e-5g-8gb-256gb-studio-quality-aura-light.svg"
    ],
    thumbnail: "/images/products/vivo-v30e-5g-8gb-256gb-studio-quality-aura-light.svg",
    specifications: { "PTA Status": "Official PTA Approved", "Sensor": "Sony IMX882 50MP OIS", "Battery": "5500 mAh Battery with 4-Year Durability" },
    features: ["Aura Light 2.0 Temperature Tuned Portrait", "3D Curved Glass Display", "Qualcomm Snapdragon 6 Gen 1"],
    warranty: "1 Year Official Vivo Warranty",
    tags: ["Vivo", "V30e", "Aura Light", "Sony IMX"],
    isFeatured: false,
    isDeal: false,
    isNew: true,
    rating: 4.8,
    reviewCount: 21,
    weight: "179 g",
    dimensions: "164.4 x 74.8 x 7.7 mm",
    color: "Giri Red",
    capacity: "8GB / 256GB",
    model: "V2339",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Realme 12+ 5G 8GB/256GB Pioneer Watch Design",
    slug: "realme-12-plus-5g-8gb-256gb-pioneer-watch-design",
    brand: "Realme",
    category: "Mobiles",
    subcategory: "5G Smartphones",
    sku: "HC-MOB-004",
    description: "Realme 12+ 5G with luxury watch inspired vegan leather back, Sony LYT-600 OIS camera, Dimensity 7050 5G chipset, and 67W charging.",
    shortDescription: "Luxury vegan leather watch design with Sony LYT-600 OIS camera sensor.",
    price: 74999,
    oldPrice: 82000,
    discountPercentage: 9,
    stock: 14,
    stockStatus: "in_stock",
    images: [
      "/images/products/realme-12-plus-5g-8gb-256gb-pioneer-watch-design.svg"
    ],
    thumbnail: "/images/products/realme-12-plus-5g-8gb-256gb-pioneer-watch-design.svg",
    specifications: { "PTA Status": "Official PTA Approved", "Camera": "Sony LYT-600 OIS Master Camera", "Charging": "67W SuperVOOC" },
    features: ["Pioneer Luxury Watch Design", "Rainwater Smart Touch Technology", "Vapor Chamber Cooling System"],
    warranty: "1 Year Official Realme Warranty",
    tags: ["Realme", "12 Plus", "Sony LYT", "Leather"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.7,
    reviewCount: 18,
    weight: "190 g",
    dimensions: "163 x 75.5 x 7.9 mm",
    color: "Navigator Beige",
    capacity: "8GB / 256GB",
    model: "RMX3867",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Infinix Note 40 Pro 8GB/256GB All-Round FastCharge",
    slug: "infinix-note-40-pro-8gb-256gb-all-round-fastcharge",
    brand: "Infinix",
    category: "Mobiles",
    subcategory: "4G/5G Smartphones",
    sku: "HC-MOB-005",
    description: "Infinix Note 40 Pro featuring 70W Multi-Speed FastCharge + 20W Wireless MagCharge, 3D curved 120Hz AMOLED screen, 108MP OIS camera, and JBL tuned audio.",
    shortDescription: "70W Wired + 20W Wireless MagCharge with 108MP OIS camera and Sound by JBL.",
    price: 69999,
    oldPrice: 76000,
    discountPercentage: 8,
    stock: 18,
    stockStatus: "in_stock",
    images: [
      "/images/products/infinix-note-40-pro-8gb-256gb-all-round-fastcharge.svg"
    ],
    thumbnail: "/images/products/infinix-note-40-pro-8gb-256gb-all-round-fastcharge.svg",
    specifications: { "PTA Status": "Official PTA Approved", "Wireless Charging": "20W Wireless MagCharge Compatible", "Audio": "Dual Speakers Tuned by JBL" },
    features: ["Active Halo AI Lighting on Back", "Cheetah X1 Power Management Chip", "Bypass Charge 2.0 for Gaming"],
    warranty: "1 Year Official Warranty",
    tags: ["Infinix", "Note 40 Pro", "Wireless MagCharge", "JBL"],
    isFeatured: true,
    isDeal: true,
    isNew: true,
    rating: 4.8,
    reviewCount: 30,
    weight: "190 g",
    dimensions: "164.3 x 74.5 x 8.1 mm",
    color: "Vintage Green Vegan Leather",
    capacity: "8GB / 256GB",
    model: "X6850",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Tecno Camon 30 Pro 12GB/512GB Imaging Master",
    slug: "tecno-camon-30-pro-12gb-512gb-imaging-master",
    brand: "Tecno",
    category: "Mobiles",
    subcategory: "5G Smartphones",
    sku: "HC-MOB-006",
    description: "Tecno Camon 30 Pro 5G with Sony IMX890 50MP OIS sensor, 50MP eye-tracking selfie camera, MediaTek Dimensity 8200 Ultimate chipset, and 144Hz AMOLED screen.",
    shortDescription: "Flagship Dimensity 8200 with 144Hz AMOLED and 50MP Sony IMX890 OIS camera.",
    price: 99999,
    oldPrice: 109000,
    discountPercentage: 8,
    stock: 11,
    stockStatus: "in_stock",
    images: [
      "/images/products/tecno-camon-30-pro-12gb-512gb-imaging-master.svg"
    ],
    thumbnail: "/images/products/tecno-camon-30-pro-12gb-512gb-imaging-master.svg",
    specifications: { "PTA Status": "Official PTA Approved", "Processor": "Dimensity 8200 Ultimate 4nm", "Display": "6.78 Inch 144Hz 1.5K AMOLED" },
    features: ["Classic Camera Aesthetic Design", "Dolby Atmos Dual Stereo Speakers", "Action Red Breathing Light Indicator"],
    warranty: "1 Year Official Tecno Warranty",
    tags: ["Tecno", "Camon 30 Pro", "144Hz", "IMX890"],
    isFeatured: false,
    isDeal: false,
    isNew: true,
    rating: 4.8,
    reviewCount: 16,
    weight: "189 g",
    dimensions: "164 x 74.4 x 7.7 mm",
    color: "Alps Snowy Silver",
    capacity: "12GB / 512GB",
    model: "CL8",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Xiaomi Redmi Note 13 Pro 8GB/256GB 200MP Camera",
    slug: "xiaomi-redmi-note-13-pro-8gb-256gb-200mp-camera",
    brand: "Xiaomi",
    category: "Mobiles",
    subcategory: "4G/5G Smartphones",
    sku: "HC-MOB-007",
    description: "Xiaomi Redmi Note 13 Pro featuring ultra-clear 200MP camera with OIS, 120Hz AMOLED display with in-screen fingerprint, 67W turbo charging, and Helio G99-Ultra.",
    shortDescription: "200MP flagship level camera with OIS, 120Hz AMOLED, and 67W in-box charger.",
    price: 74999,
    oldPrice: 82000,
    discountPercentage: 9,
    stock: 17,
    stockStatus: "in_stock",
    images: [
      "/images/products/xiaomi-redmi-note-13-pro-8gb-256gb-200mp-camera.svg"
    ],
    thumbnail: "/images/products/xiaomi-redmi-note-13-pro-8gb-256gb-200mp-camera.svg",
    specifications: { "PTA Status": "Official PTA Approved", "Camera": "200MP Ultra-Clear with OIS + EIS", "Charging": "67W Turbo Charge In Box" },
    features: ["Lossless 4x Optical-grade Sensor Zoom", "Corning Gorilla Glass 5 Protection", "In-Screen Fingerprint Sensor"],
    warranty: "1 Year Official Xiaomi Warranty",
    tags: ["Xiaomi", "Redmi Note 13 Pro", "200MP", "Best Seller"],
    isFeatured: true,
    isDeal: true,
    isNew: false,
    rating: 4.9,
    reviewCount: 36,
    weight: "188 g",
    dimensions: "161.1 x 75 x 8 mm",
    color: "Midnight Black",
    capacity: "8GB / 256GB",
    model: "23117RA68G",
    installationAvailable: false,
    deliveryAvailable: true
  },

  // 90-92: SMART WATCHES
  {
    name: "Samsung Galaxy Watch 6 Classic 47mm Bluetooth",
    slug: "samsung-galaxy-watch-6-classic-47mm-bluetooth",
    brand: "Samsung",
    category: "Smart Watches",
    subcategory: "Wearables",
    sku: "HC-WCH-001",
    description: "Samsung Galaxy Watch 6 Classic 47mm with physical rotating bezel, Sapphire Crystal AMOLED display, ECG heart monitoring, Body Composition BIA sensor, and Wear OS powered by Google.",
    shortDescription: "Timeless physical rotating bezel smartwatch with Sapphire Crystal and advanced health monitoring.",
    price: 68000,
    oldPrice: 75000,
    discountPercentage: 9,
    stock: 12,
    stockStatus: "in_stock",
    images: [
      "/images/products/samsung-galaxy-watch-6-classic-47mm-bluetooth.svg"
    ],
    thumbnail: "/images/products/samsung-galaxy-watch-6-classic-47mm-bluetooth.svg",
    specifications: { "Display": "1.5 Inch Super AMOLED Sapphire Glass", "Bezel": "Physical Rotating Stainless Steel", "Sensors": "BIA Body Composition, ECG, Heart Rate, SpO2, Skin Temp" },
    features: ["Physical Rotating Bezel Control", "Google Play Store Wear OS Apps", "IP68 & 5ATM Water Resistance"],
    warranty: "1 Year Samsung Warranty",
    tags: ["Samsung", "Watch 6 Classic", "Wear OS", "ECG"],
    isFeatured: true,
    isDeal: false,
    isNew: true,
    rating: 4.9,
    reviewCount: 25,
    weight: "59 g",
    dimensions: "46.5 x 46.5 x 10.9 mm",
    color: "Silver Stainless Steel",
    capacity: "47mm",
    model: "SM-R960",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Xiaomi Smart Watch S3 AMOLED Bluetooth Calling",
    slug: "xiaomi-smart-watch-s3-amoled-bluetooth-calling",
    brand: "Xiaomi",
    category: "Smart Watches",
    subcategory: "Wearables",
    sku: "HC-WCH-002",
    description: "Xiaomi Watch S3 with interchangeable bezel design, 1.43-inch 60Hz AMOLED screen, up to 15 days battery life, 5-system GNSS satellite positioning, and crisp Bluetooth calls.",
    shortDescription: "Interchangeable bezel smartwatch with 15-day battery and dual-frequency satellite GPS.",
    price: 34000,
    oldPrice: 38000,
    discountPercentage: 11,
    stock: 16,
    stockStatus: "in_stock",
    images: [
      "/images/products/xiaomi-smart-watch-s3-amoled-bluetooth-calling.svg"
    ],
    thumbnail: "/images/products/xiaomi-smart-watch-s3-amoled-bluetooth-calling.svg",
    specifications: { "Display": "1.43 Inch 60Hz AMOLED", "Battery Life": "Up to 15 Days", "Water Resistance": "5 ATM Swim Proof" },
    features: ["Swap-On Swappable Bezel Rings", "Hands-Free Bluetooth Calling & Speaker", "150+ Sports Tracking Modes"],
    warranty: "1 Year Official Warranty",
    tags: ["Xiaomi", "Watch S3", "AMOLED", "Calling"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.8,
    reviewCount: 20,
    weight: "44 g",
    dimensions: "47 x 47 x 12 mm",
    color: "Midnight Black",
    capacity: "Standard 47mm",
    model: "M2323W1",
    installationAvailable: false,
    deliveryAvailable: true
  },
  {
    name: "Apple Watch SE 2nd Gen 44mm GPS",
    slug: "apple-watch-se-2nd-gen-44mm-gps",
    brand: "Apple",
    category: "Smart Watches",
    subcategory: "Wearables",
    sku: "HC-WCH-003",
    description: "Apple Watch SE (2nd Gen) 44mm with Retina OLED display, Crash Detection, Workout app metrics, heart rate notifications, and seamless iPhone ecosystem pairing.",
    shortDescription: "Official Apple Watch SE with Retina OLED display and Crash Detection safety.",
    price: 88000,
    oldPrice: 96000,
    discountPercentage: 8,
    stock: 10,
    stockStatus: "in_stock",
    images: [
      "/images/products/apple-watch-se-2nd-gen-44mm-gps.svg"
    ],
    thumbnail: "/images/products/apple-watch-se-2nd-gen-44mm-gps.svg",
    specifications: { "Size": "44mm Aluminum Case", "Chip": "S8 SiP Dual Core", "Water Resistance": "50m Swimproof" },
    features: ["Crash Detection & Emergency SOS", "Fall Detection Sensors", "Activity Rings Motivation"],
    warranty: "1 Year International Apple Warranty",
    tags: ["Apple", "Watch SE", "44mm", "GPS"],
    isFeatured: true,
    isDeal: false,
    isNew: false,
    rating: 4.9,
    reviewCount: 28,
    weight: "33 g",
    dimensions: "44 x 38 x 10.7 mm",
    color: "Midnight Aluminum",
    capacity: "44mm",
    model: "A2723",
    installationAvailable: false,
    deliveryAvailable: true
  },

  // 93-95: FITNESS
  {
    name: "Motorized Treadmill Heavy Duty 3.0 HP with Auto Incline",
    slug: "motorized-treadmill-heavy-duty-3-0-hp-with-auto-incline",
    brand: "PowerMax",
    category: "Fitness Machines",
    subcategory: "Treadmills",
    sku: "HC-FIT-001",
    description: "Commercial-grade 3.0 HP continuous peak AC motor treadmill with 1-15% motorized auto incline, hydraulic soft-drop folding, 130kg max user weight, and MP3 Bluetooth speakers.",
    shortDescription: "Heavy-duty 3.0 HP motorized treadmill with auto incline, shock absorbers, and folding frame.",
    price: 185000,
    oldPrice: 205000,
    discountPercentage: 10,
    stock: 6,
    stockStatus: "in_stock",
    images: [
      "/images/products/motorized-treadmill-heavy-duty-3-0-hp-with-auto-incline.svg"
    ],
    thumbnail: "/images/products/motorized-treadmill-heavy-duty-3-0-hp-with-auto-incline.svg",
    specifications: { "Motor": "3.0 HP Peak Quiet Duty Motor", "Max Speed": "16 km/h", "Max User Weight": "130 KG", "Incline": "1-15 Levels Motorized Auto Incline" },
    features: ["Multi-Point Knee Protection Shock Absorption", "Hydraulic Soft-Drop Easy Folding", "Built-in Massager & Sit-up Stand"],
    warranty: "2 Years Motor Warranty, 1 Year Frame",
    tags: ["Treadmill", "Fitness", "3.0 HP", "Auto Incline"],
    isFeatured: true,
    isDeal: true,
    isNew: false,
    rating: 4.8,
    reviewCount: 16,
    weight: "68 kg",
    dimensions: "1650 x 740 x 1320 mm",
    color: "Black & Silver",
    capacity: "130 KG Max Weight",
    model: "T-3000-PRO",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Elliptical Cross Trainer Machine Magnetic Resistance",
    slug: "elliptical-cross-trainer-machine-magnetic-resistance",
    brand: "PowerMax",
    category: "Fitness Machines",
    subcategory: "Ellipticals",
    sku: "HC-FIT-002",
    description: "2-in-1 elliptical cross trainer and exercise bike with 8-level smooth magnetic flywheel resistance, hand pulse sensors, and LCD tracking console.",
    shortDescription: "Zero-impact joint-friendly magnetic cross trainer with dual handle movement.",
    price: 85000,
    oldPrice: 94000,
    discountPercentage: 10,
    stock: 8,
    stockStatus: "in_stock",
    images: [
      "/images/products/elliptical-cross-trainer-machine-magnetic-resistance.svg"
    ],
    thumbnail: "/images/products/elliptical-cross-trainer-machine-magnetic-resistance.svg",
    specifications: { "Flywheel": "7 KG Heavy Inertia Flywheel", "Resistance": "8-Level Precision Magnetic", "Max Weight": "115 KG" },
    features: ["Zero-Impact Joint Friendly Cardio", "Pulse Rate Monitor on Grips", "Anti-Slip Textured Foot Pedals"],
    warranty: "1 Year Frame & Mechanism Warranty",
    tags: ["Elliptical", "Cross Trainer", "Cardio"],
    isFeatured: false,
    isDeal: false,
    isNew: true,
    rating: 4.7,
    reviewCount: 14,
    weight: "36 kg",
    dimensions: "1150 x 600 x 1550 mm",
    color: "Grey & Neon Yellow",
    capacity: "115 KG",
    model: "EL-500",
    installationAvailable: true,
    deliveryAvailable: true
  },
  {
    name: "Exercise Spin Bike Magnetic Heavy Flywheel",
    slug: "exercise-spin-bike-magnetic-heavy-flywheel",
    brand: "PowerMax",
    category: "Fitness Machines",
    subcategory: "Exercise Bikes",
    sku: "HC-FIT-003",
    description: "Indoor cycling spin bike featuring 13kg bidirectional flywheel, quiet belt drive system, infinite resistance dial, and adjustable handlebar and padded saddle.",
    shortDescription: "Indoor cycling studio spin bike with 13kg flywheel and silent belt drive.",
    price: 62000,
    oldPrice: 69000,
    discountPercentage: 10,
    stock: 10,
    stockStatus: "in_stock",
    images: [
      "/images/products/exercise-spin-bike-magnetic-heavy-flywheel.svg"
    ],
    thumbnail: "/images/products/exercise-spin-bike-magnetic-heavy-flywheel.svg",
    specifications: { "Flywheel": "13 KG Precision Balanced Steel", "Drive": "Silent Poly-V Belt Drive", "Max Weight": "125 KG" },
    features: ["Stepless Continuous Tension Knob", "4-Way Adjustable Comfort Saddle", "Front Transport Wheels"],
    warranty: "1 Year Warranty",
    tags: ["Spin Bike", "Exercise Bike", "Cycling"],
    isFeatured: false,
    isDeal: true,
    isNew: false,
    rating: 4.8,
    reviewCount: 17,
    weight: "31 kg",
    dimensions: "1050 x 510 x 1150 mm",
    color: "Matte Black & Red",
    capacity: "125 KG",
    model: "SPIN-800",
    installationAvailable: true,
    deliveryAvailable: true
  }
];
